// Code generated by ent, DO NOT EDIT.

package core

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the core type in the database.
	Label = "core"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPolicyFloor holds the string denoting the policy_floor field in the database.
	FieldPolicyFloor = "policy_floor"
	// FieldAuthorization holds the string denoting the authorization field in the database.
	FieldAuthorization = "authorization"
	// FieldAppliedRevision holds the string denoting the applied_revision field in the database.
	FieldAppliedRevision = "applied_revision"
	// FieldAppliedPolicy holds the string denoting the applied_policy field in the database.
	FieldAppliedPolicy = "applied_policy"
	// FieldAppliedConfig holds the string denoting the applied_config field in the database.
	FieldAppliedConfig = "applied_config"
	// FieldStage holds the string denoting the stage field in the database.
	FieldStage = "stage"
	// FieldPendingTask holds the string denoting the pending_task field in the database.
	FieldPendingTask = "pending_task"
	// FieldPendingRevision holds the string denoting the pending_revision field in the database.
	FieldPendingRevision = "pending_revision"
	// FieldPendingPolicy holds the string denoting the pending_policy field in the database.
	FieldPendingPolicy = "pending_policy"
	// FieldPendingConfig holds the string denoting the pending_config field in the database.
	FieldPendingConfig = "pending_config"
	// Table holds the table name of the core in the database.
	Table = "cores"
)

// Columns holds all SQL columns for core fields.
var Columns = []string{
	FieldID,
	FieldPolicyFloor,
	FieldAuthorization,
	FieldAppliedRevision,
	FieldAppliedPolicy,
	FieldAppliedConfig,
	FieldStage,
	FieldPendingTask,
	FieldPendingRevision,
	FieldPendingPolicy,
	FieldPendingConfig,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPolicyFloor holds the default value on creation for the "policy_floor" field.
	DefaultPolicyFloor int64
	// PolicyFloorValidator is a validator for the "policy_floor" field. It is called by the builders before save.
	PolicyFloorValidator func(int64) error
	// DefaultAppliedRevision holds the default value on creation for the "applied_revision" field.
	DefaultAppliedRevision string
	// DefaultAppliedPolicy holds the default value on creation for the "applied_policy" field.
	DefaultAppliedPolicy int64
	// AppliedPolicyValidator is a validator for the "applied_policy" field. It is called by the builders before save.
	AppliedPolicyValidator func(int64) error
	// DefaultStage holds the default value on creation for the "stage" field.
	DefaultStage string
	// DefaultPendingTask holds the default value on creation for the "pending_task" field.
	DefaultPendingTask string
	// DefaultPendingRevision holds the default value on creation for the "pending_revision" field.
	DefaultPendingRevision string
	// DefaultPendingPolicy holds the default value on creation for the "pending_policy" field.
	DefaultPendingPolicy int64
	// PendingPolicyValidator is a validator for the "pending_policy" field. It is called by the builders before save.
	PendingPolicyValidator func(int64) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Core queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPolicyFloor orders the results by the policy_floor field.
func ByPolicyFloor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyFloor, opts...).ToFunc()
}

// ByAppliedRevision orders the results by the applied_revision field.
func ByAppliedRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedRevision, opts...).ToFunc()
}

// ByAppliedPolicy orders the results by the applied_policy field.
func ByAppliedPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedPolicy, opts...).ToFunc()
}

// ByStage orders the results by the stage field.
func ByStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStage, opts...).ToFunc()
}

// ByPendingTask orders the results by the pending_task field.
func ByPendingTask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingTask, opts...).ToFunc()
}

// ByPendingRevision orders the results by the pending_revision field.
func ByPendingRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingRevision, opts...).ToFunc()
}

// ByPendingPolicy orders the results by the pending_policy field.
func ByPendingPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingPolicy, opts...).ToFunc()
}
