// Code generated by ent, DO NOT EDIT.

package core

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Core {
	return predicate.Core(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Core {
	return predicate.Core(sql.FieldContainsFold(FieldID, id))
}

// PolicyFloor applies equality check predicate on the "policy_floor" field. It's identical to PolicyFloorEQ.
func PolicyFloor(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPolicyFloor, v))
}

// Authorization applies equality check predicate on the "authorization" field. It's identical to AuthorizationEQ.
func Authorization(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAuthorization, v))
}

// AppliedRevision applies equality check predicate on the "applied_revision" field. It's identical to AppliedRevisionEQ.
func AppliedRevision(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedRevision, v))
}

// AppliedPolicy applies equality check predicate on the "applied_policy" field. It's identical to AppliedPolicyEQ.
func AppliedPolicy(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedPolicy, v))
}

// AppliedConfig applies equality check predicate on the "applied_config" field. It's identical to AppliedConfigEQ.
func AppliedConfig(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedConfig, v))
}

// Stage applies equality check predicate on the "stage" field. It's identical to StageEQ.
func Stage(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldStage, v))
}

// PendingTask applies equality check predicate on the "pending_task" field. It's identical to PendingTaskEQ.
func PendingTask(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingTask, v))
}

// PendingRevision applies equality check predicate on the "pending_revision" field. It's identical to PendingRevisionEQ.
func PendingRevision(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingRevision, v))
}

// PendingPolicy applies equality check predicate on the "pending_policy" field. It's identical to PendingPolicyEQ.
func PendingPolicy(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingPolicy, v))
}

// PendingConfig applies equality check predicate on the "pending_config" field. It's identical to PendingConfigEQ.
func PendingConfig(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingConfig, v))
}

// PolicyFloorEQ applies the EQ predicate on the "policy_floor" field.
func PolicyFloorEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPolicyFloor, v))
}

// PolicyFloorNEQ applies the NEQ predicate on the "policy_floor" field.
func PolicyFloorNEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldPolicyFloor, v))
}

// PolicyFloorIn applies the In predicate on the "policy_floor" field.
func PolicyFloorIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldPolicyFloor, vs...))
}

// PolicyFloorNotIn applies the NotIn predicate on the "policy_floor" field.
func PolicyFloorNotIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldPolicyFloor, vs...))
}

// PolicyFloorGT applies the GT predicate on the "policy_floor" field.
func PolicyFloorGT(v int64) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldPolicyFloor, v))
}

// PolicyFloorGTE applies the GTE predicate on the "policy_floor" field.
func PolicyFloorGTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldPolicyFloor, v))
}

// PolicyFloorLT applies the LT predicate on the "policy_floor" field.
func PolicyFloorLT(v int64) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldPolicyFloor, v))
}

// PolicyFloorLTE applies the LTE predicate on the "policy_floor" field.
func PolicyFloorLTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldPolicyFloor, v))
}

// AuthorizationEQ applies the EQ predicate on the "authorization" field.
func AuthorizationEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAuthorization, v))
}

// AuthorizationNEQ applies the NEQ predicate on the "authorization" field.
func AuthorizationNEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldAuthorization, v))
}

// AuthorizationIn applies the In predicate on the "authorization" field.
func AuthorizationIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldAuthorization, vs...))
}

// AuthorizationNotIn applies the NotIn predicate on the "authorization" field.
func AuthorizationNotIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldAuthorization, vs...))
}

// AuthorizationGT applies the GT predicate on the "authorization" field.
func AuthorizationGT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldAuthorization, v))
}

// AuthorizationGTE applies the GTE predicate on the "authorization" field.
func AuthorizationGTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldAuthorization, v))
}

// AuthorizationLT applies the LT predicate on the "authorization" field.
func AuthorizationLT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldAuthorization, v))
}

// AuthorizationLTE applies the LTE predicate on the "authorization" field.
func AuthorizationLTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldAuthorization, v))
}

// AuthorizationIsNil applies the IsNil predicate on the "authorization" field.
func AuthorizationIsNil() predicate.Core {
	return predicate.Core(sql.FieldIsNull(FieldAuthorization))
}

// AuthorizationNotNil applies the NotNil predicate on the "authorization" field.
func AuthorizationNotNil() predicate.Core {
	return predicate.Core(sql.FieldNotNull(FieldAuthorization))
}

// AppliedRevisionEQ applies the EQ predicate on the "applied_revision" field.
func AppliedRevisionEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedRevision, v))
}

// AppliedRevisionNEQ applies the NEQ predicate on the "applied_revision" field.
func AppliedRevisionNEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldAppliedRevision, v))
}

// AppliedRevisionIn applies the In predicate on the "applied_revision" field.
func AppliedRevisionIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldAppliedRevision, vs...))
}

// AppliedRevisionNotIn applies the NotIn predicate on the "applied_revision" field.
func AppliedRevisionNotIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldAppliedRevision, vs...))
}

// AppliedRevisionGT applies the GT predicate on the "applied_revision" field.
func AppliedRevisionGT(v string) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldAppliedRevision, v))
}

// AppliedRevisionGTE applies the GTE predicate on the "applied_revision" field.
func AppliedRevisionGTE(v string) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldAppliedRevision, v))
}

// AppliedRevisionLT applies the LT predicate on the "applied_revision" field.
func AppliedRevisionLT(v string) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldAppliedRevision, v))
}

// AppliedRevisionLTE applies the LTE predicate on the "applied_revision" field.
func AppliedRevisionLTE(v string) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldAppliedRevision, v))
}

// AppliedRevisionContains applies the Contains predicate on the "applied_revision" field.
func AppliedRevisionContains(v string) predicate.Core {
	return predicate.Core(sql.FieldContains(FieldAppliedRevision, v))
}

// AppliedRevisionHasPrefix applies the HasPrefix predicate on the "applied_revision" field.
func AppliedRevisionHasPrefix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasPrefix(FieldAppliedRevision, v))
}

// AppliedRevisionHasSuffix applies the HasSuffix predicate on the "applied_revision" field.
func AppliedRevisionHasSuffix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasSuffix(FieldAppliedRevision, v))
}

// AppliedRevisionEqualFold applies the EqualFold predicate on the "applied_revision" field.
func AppliedRevisionEqualFold(v string) predicate.Core {
	return predicate.Core(sql.FieldEqualFold(FieldAppliedRevision, v))
}

// AppliedRevisionContainsFold applies the ContainsFold predicate on the "applied_revision" field.
func AppliedRevisionContainsFold(v string) predicate.Core {
	return predicate.Core(sql.FieldContainsFold(FieldAppliedRevision, v))
}

// AppliedPolicyEQ applies the EQ predicate on the "applied_policy" field.
func AppliedPolicyEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedPolicy, v))
}

// AppliedPolicyNEQ applies the NEQ predicate on the "applied_policy" field.
func AppliedPolicyNEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldAppliedPolicy, v))
}

// AppliedPolicyIn applies the In predicate on the "applied_policy" field.
func AppliedPolicyIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldAppliedPolicy, vs...))
}

// AppliedPolicyNotIn applies the NotIn predicate on the "applied_policy" field.
func AppliedPolicyNotIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldAppliedPolicy, vs...))
}

// AppliedPolicyGT applies the GT predicate on the "applied_policy" field.
func AppliedPolicyGT(v int64) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldAppliedPolicy, v))
}

// AppliedPolicyGTE applies the GTE predicate on the "applied_policy" field.
func AppliedPolicyGTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldAppliedPolicy, v))
}

// AppliedPolicyLT applies the LT predicate on the "applied_policy" field.
func AppliedPolicyLT(v int64) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldAppliedPolicy, v))
}

// AppliedPolicyLTE applies the LTE predicate on the "applied_policy" field.
func AppliedPolicyLTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldAppliedPolicy, v))
}

// AppliedConfigEQ applies the EQ predicate on the "applied_config" field.
func AppliedConfigEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldAppliedConfig, v))
}

// AppliedConfigNEQ applies the NEQ predicate on the "applied_config" field.
func AppliedConfigNEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldAppliedConfig, v))
}

// AppliedConfigIn applies the In predicate on the "applied_config" field.
func AppliedConfigIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldAppliedConfig, vs...))
}

// AppliedConfigNotIn applies the NotIn predicate on the "applied_config" field.
func AppliedConfigNotIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldAppliedConfig, vs...))
}

// AppliedConfigGT applies the GT predicate on the "applied_config" field.
func AppliedConfigGT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldAppliedConfig, v))
}

// AppliedConfigGTE applies the GTE predicate on the "applied_config" field.
func AppliedConfigGTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldAppliedConfig, v))
}

// AppliedConfigLT applies the LT predicate on the "applied_config" field.
func AppliedConfigLT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldAppliedConfig, v))
}

// AppliedConfigLTE applies the LTE predicate on the "applied_config" field.
func AppliedConfigLTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldAppliedConfig, v))
}

// AppliedConfigIsNil applies the IsNil predicate on the "applied_config" field.
func AppliedConfigIsNil() predicate.Core {
	return predicate.Core(sql.FieldIsNull(FieldAppliedConfig))
}

// AppliedConfigNotNil applies the NotNil predicate on the "applied_config" field.
func AppliedConfigNotNil() predicate.Core {
	return predicate.Core(sql.FieldNotNull(FieldAppliedConfig))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldStage, vs...))
}

// StageGT applies the GT predicate on the "stage" field.
func StageGT(v string) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldStage, v))
}

// StageGTE applies the GTE predicate on the "stage" field.
func StageGTE(v string) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldStage, v))
}

// StageLT applies the LT predicate on the "stage" field.
func StageLT(v string) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldStage, v))
}

// StageLTE applies the LTE predicate on the "stage" field.
func StageLTE(v string) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldStage, v))
}

// StageContains applies the Contains predicate on the "stage" field.
func StageContains(v string) predicate.Core {
	return predicate.Core(sql.FieldContains(FieldStage, v))
}

// StageHasPrefix applies the HasPrefix predicate on the "stage" field.
func StageHasPrefix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasPrefix(FieldStage, v))
}

// StageHasSuffix applies the HasSuffix predicate on the "stage" field.
func StageHasSuffix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasSuffix(FieldStage, v))
}

// StageEqualFold applies the EqualFold predicate on the "stage" field.
func StageEqualFold(v string) predicate.Core {
	return predicate.Core(sql.FieldEqualFold(FieldStage, v))
}

// StageContainsFold applies the ContainsFold predicate on the "stage" field.
func StageContainsFold(v string) predicate.Core {
	return predicate.Core(sql.FieldContainsFold(FieldStage, v))
}

// PendingTaskEQ applies the EQ predicate on the "pending_task" field.
func PendingTaskEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingTask, v))
}

// PendingTaskNEQ applies the NEQ predicate on the "pending_task" field.
func PendingTaskNEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldPendingTask, v))
}

// PendingTaskIn applies the In predicate on the "pending_task" field.
func PendingTaskIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldPendingTask, vs...))
}

// PendingTaskNotIn applies the NotIn predicate on the "pending_task" field.
func PendingTaskNotIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldPendingTask, vs...))
}

// PendingTaskGT applies the GT predicate on the "pending_task" field.
func PendingTaskGT(v string) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldPendingTask, v))
}

// PendingTaskGTE applies the GTE predicate on the "pending_task" field.
func PendingTaskGTE(v string) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldPendingTask, v))
}

// PendingTaskLT applies the LT predicate on the "pending_task" field.
func PendingTaskLT(v string) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldPendingTask, v))
}

// PendingTaskLTE applies the LTE predicate on the "pending_task" field.
func PendingTaskLTE(v string) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldPendingTask, v))
}

// PendingTaskContains applies the Contains predicate on the "pending_task" field.
func PendingTaskContains(v string) predicate.Core {
	return predicate.Core(sql.FieldContains(FieldPendingTask, v))
}

// PendingTaskHasPrefix applies the HasPrefix predicate on the "pending_task" field.
func PendingTaskHasPrefix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasPrefix(FieldPendingTask, v))
}

// PendingTaskHasSuffix applies the HasSuffix predicate on the "pending_task" field.
func PendingTaskHasSuffix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasSuffix(FieldPendingTask, v))
}

// PendingTaskEqualFold applies the EqualFold predicate on the "pending_task" field.
func PendingTaskEqualFold(v string) predicate.Core {
	return predicate.Core(sql.FieldEqualFold(FieldPendingTask, v))
}

// PendingTaskContainsFold applies the ContainsFold predicate on the "pending_task" field.
func PendingTaskContainsFold(v string) predicate.Core {
	return predicate.Core(sql.FieldContainsFold(FieldPendingTask, v))
}

// PendingRevisionEQ applies the EQ predicate on the "pending_revision" field.
func PendingRevisionEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingRevision, v))
}

// PendingRevisionNEQ applies the NEQ predicate on the "pending_revision" field.
func PendingRevisionNEQ(v string) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldPendingRevision, v))
}

// PendingRevisionIn applies the In predicate on the "pending_revision" field.
func PendingRevisionIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldPendingRevision, vs...))
}

// PendingRevisionNotIn applies the NotIn predicate on the "pending_revision" field.
func PendingRevisionNotIn(vs ...string) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldPendingRevision, vs...))
}

// PendingRevisionGT applies the GT predicate on the "pending_revision" field.
func PendingRevisionGT(v string) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldPendingRevision, v))
}

// PendingRevisionGTE applies the GTE predicate on the "pending_revision" field.
func PendingRevisionGTE(v string) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldPendingRevision, v))
}

// PendingRevisionLT applies the LT predicate on the "pending_revision" field.
func PendingRevisionLT(v string) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldPendingRevision, v))
}

// PendingRevisionLTE applies the LTE predicate on the "pending_revision" field.
func PendingRevisionLTE(v string) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldPendingRevision, v))
}

// PendingRevisionContains applies the Contains predicate on the "pending_revision" field.
func PendingRevisionContains(v string) predicate.Core {
	return predicate.Core(sql.FieldContains(FieldPendingRevision, v))
}

// PendingRevisionHasPrefix applies the HasPrefix predicate on the "pending_revision" field.
func PendingRevisionHasPrefix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasPrefix(FieldPendingRevision, v))
}

// PendingRevisionHasSuffix applies the HasSuffix predicate on the "pending_revision" field.
func PendingRevisionHasSuffix(v string) predicate.Core {
	return predicate.Core(sql.FieldHasSuffix(FieldPendingRevision, v))
}

// PendingRevisionEqualFold applies the EqualFold predicate on the "pending_revision" field.
func PendingRevisionEqualFold(v string) predicate.Core {
	return predicate.Core(sql.FieldEqualFold(FieldPendingRevision, v))
}

// PendingRevisionContainsFold applies the ContainsFold predicate on the "pending_revision" field.
func PendingRevisionContainsFold(v string) predicate.Core {
	return predicate.Core(sql.FieldContainsFold(FieldPendingRevision, v))
}

// PendingPolicyEQ applies the EQ predicate on the "pending_policy" field.
func PendingPolicyEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingPolicy, v))
}

// PendingPolicyNEQ applies the NEQ predicate on the "pending_policy" field.
func PendingPolicyNEQ(v int64) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldPendingPolicy, v))
}

// PendingPolicyIn applies the In predicate on the "pending_policy" field.
func PendingPolicyIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldPendingPolicy, vs...))
}

// PendingPolicyNotIn applies the NotIn predicate on the "pending_policy" field.
func PendingPolicyNotIn(vs ...int64) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldPendingPolicy, vs...))
}

// PendingPolicyGT applies the GT predicate on the "pending_policy" field.
func PendingPolicyGT(v int64) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldPendingPolicy, v))
}

// PendingPolicyGTE applies the GTE predicate on the "pending_policy" field.
func PendingPolicyGTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldPendingPolicy, v))
}

// PendingPolicyLT applies the LT predicate on the "pending_policy" field.
func PendingPolicyLT(v int64) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldPendingPolicy, v))
}

// PendingPolicyLTE applies the LTE predicate on the "pending_policy" field.
func PendingPolicyLTE(v int64) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldPendingPolicy, v))
}

// PendingConfigEQ applies the EQ predicate on the "pending_config" field.
func PendingConfigEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldEQ(FieldPendingConfig, v))
}

// PendingConfigNEQ applies the NEQ predicate on the "pending_config" field.
func PendingConfigNEQ(v []byte) predicate.Core {
	return predicate.Core(sql.FieldNEQ(FieldPendingConfig, v))
}

// PendingConfigIn applies the In predicate on the "pending_config" field.
func PendingConfigIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldIn(FieldPendingConfig, vs...))
}

// PendingConfigNotIn applies the NotIn predicate on the "pending_config" field.
func PendingConfigNotIn(vs ...[]byte) predicate.Core {
	return predicate.Core(sql.FieldNotIn(FieldPendingConfig, vs...))
}

// PendingConfigGT applies the GT predicate on the "pending_config" field.
func PendingConfigGT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGT(FieldPendingConfig, v))
}

// PendingConfigGTE applies the GTE predicate on the "pending_config" field.
func PendingConfigGTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldGTE(FieldPendingConfig, v))
}

// PendingConfigLT applies the LT predicate on the "pending_config" field.
func PendingConfigLT(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLT(FieldPendingConfig, v))
}

// PendingConfigLTE applies the LTE predicate on the "pending_config" field.
func PendingConfigLTE(v []byte) predicate.Core {
	return predicate.Core(sql.FieldLTE(FieldPendingConfig, v))
}

// PendingConfigIsNil applies the IsNil predicate on the "pending_config" field.
func PendingConfigIsNil() predicate.Core {
	return predicate.Core(sql.FieldIsNull(FieldPendingConfig))
}

// PendingConfigNotNil applies the NotNil predicate on the "pending_config" field.
func PendingConfigNotNil() predicate.Core {
	return predicate.Core(sql.FieldNotNull(FieldPendingConfig))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Core) predicate.Core {
	return predicate.Core(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Core) predicate.Core {
	return predicate.Core(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Core) predicate.Core {
	return predicate.Core(sql.NotPredicates(p))
}
