// Code generated by ent, DO NOT EDIT.

package cursor

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cursor type in the database.
	Label = "cursor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRuntimeID holds the string denoting the runtime_id field in the database.
	FieldRuntimeID = "runtime_id"
	// FieldUpload holds the string denoting the upload field in the database.
	FieldUpload = "upload"
	// FieldDownload holds the string denoting the download field in the database.
	FieldDownload = "download"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldClosed holds the string denoting the closed field in the database.
	FieldClosed = "closed"
	// Table holds the table name of the cursor in the database.
	Table = "cursors"
)

// Columns holds all SQL columns for cursor fields.
var Columns = []string{
	FieldID,
	FieldRuntimeID,
	FieldUpload,
	FieldDownload,
	FieldObservedAt,
	FieldClosed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RuntimeIDValidator is a validator for the "runtime_id" field. It is called by the builders before save.
	RuntimeIDValidator func(string) error
	// UploadValidator is a validator for the "upload" field. It is called by the builders before save.
	UploadValidator func(int64) error
	// DownloadValidator is a validator for the "download" field. It is called by the builders before save.
	DownloadValidator func(int64) error
	// DefaultClosed holds the default value on creation for the "closed" field.
	DefaultClosed bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Cursor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRuntimeID orders the results by the runtime_id field.
func ByRuntimeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeID, opts...).ToFunc()
}

// ByUpload orders the results by the upload field.
func ByUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpload, opts...).ToFunc()
}

// ByDownload orders the results by the download field.
func ByDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownload, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByClosed orders the results by the closed field.
func ByClosed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosed, opts...).ToFunc()
}
