// Code generated by ent, DO NOT EDIT.

package cursor

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Cursor {
	return predicate.Cursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Cursor {
	return predicate.Cursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Cursor {
	return predicate.Cursor(sql.FieldContainsFold(FieldID, id))
}

// RuntimeID applies equality check predicate on the "runtime_id" field. It's identical to RuntimeIDEQ.
func RuntimeID(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldRuntimeID, v))
}

// Upload applies equality check predicate on the "upload" field. It's identical to UploadEQ.
func Upload(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldUpload, v))
}

// Download applies equality check predicate on the "download" field. It's identical to DownloadEQ.
func Download(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldDownload, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldObservedAt, v))
}

// Closed applies equality check predicate on the "closed" field. It's identical to ClosedEQ.
func Closed(v bool) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldClosed, v))
}

// RuntimeIDEQ applies the EQ predicate on the "runtime_id" field.
func RuntimeIDEQ(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldRuntimeID, v))
}

// RuntimeIDNEQ applies the NEQ predicate on the "runtime_id" field.
func RuntimeIDNEQ(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldRuntimeID, v))
}

// RuntimeIDIn applies the In predicate on the "runtime_id" field.
func RuntimeIDIn(vs ...string) predicate.Cursor {
	return predicate.Cursor(sql.FieldIn(FieldRuntimeID, vs...))
}

// RuntimeIDNotIn applies the NotIn predicate on the "runtime_id" field.
func RuntimeIDNotIn(vs ...string) predicate.Cursor {
	return predicate.Cursor(sql.FieldNotIn(FieldRuntimeID, vs...))
}

// RuntimeIDGT applies the GT predicate on the "runtime_id" field.
func RuntimeIDGT(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldGT(FieldRuntimeID, v))
}

// RuntimeIDGTE applies the GTE predicate on the "runtime_id" field.
func RuntimeIDGTE(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldGTE(FieldRuntimeID, v))
}

// RuntimeIDLT applies the LT predicate on the "runtime_id" field.
func RuntimeIDLT(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldLT(FieldRuntimeID, v))
}

// RuntimeIDLTE applies the LTE predicate on the "runtime_id" field.
func RuntimeIDLTE(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldLTE(FieldRuntimeID, v))
}

// RuntimeIDContains applies the Contains predicate on the "runtime_id" field.
func RuntimeIDContains(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldContains(FieldRuntimeID, v))
}

// RuntimeIDHasPrefix applies the HasPrefix predicate on the "runtime_id" field.
func RuntimeIDHasPrefix(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldHasPrefix(FieldRuntimeID, v))
}

// RuntimeIDHasSuffix applies the HasSuffix predicate on the "runtime_id" field.
func RuntimeIDHasSuffix(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldHasSuffix(FieldRuntimeID, v))
}

// RuntimeIDEqualFold applies the EqualFold predicate on the "runtime_id" field.
func RuntimeIDEqualFold(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldEqualFold(FieldRuntimeID, v))
}

// RuntimeIDContainsFold applies the ContainsFold predicate on the "runtime_id" field.
func RuntimeIDContainsFold(v string) predicate.Cursor {
	return predicate.Cursor(sql.FieldContainsFold(FieldRuntimeID, v))
}

// UploadEQ applies the EQ predicate on the "upload" field.
func UploadEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldUpload, v))
}

// UploadNEQ applies the NEQ predicate on the "upload" field.
func UploadNEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldUpload, v))
}

// UploadIn applies the In predicate on the "upload" field.
func UploadIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldIn(FieldUpload, vs...))
}

// UploadNotIn applies the NotIn predicate on the "upload" field.
func UploadNotIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNotIn(FieldUpload, vs...))
}

// UploadGT applies the GT predicate on the "upload" field.
func UploadGT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGT(FieldUpload, v))
}

// UploadGTE applies the GTE predicate on the "upload" field.
func UploadGTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGTE(FieldUpload, v))
}

// UploadLT applies the LT predicate on the "upload" field.
func UploadLT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLT(FieldUpload, v))
}

// UploadLTE applies the LTE predicate on the "upload" field.
func UploadLTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLTE(FieldUpload, v))
}

// DownloadEQ applies the EQ predicate on the "download" field.
func DownloadEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldDownload, v))
}

// DownloadNEQ applies the NEQ predicate on the "download" field.
func DownloadNEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldDownload, v))
}

// DownloadIn applies the In predicate on the "download" field.
func DownloadIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldIn(FieldDownload, vs...))
}

// DownloadNotIn applies the NotIn predicate on the "download" field.
func DownloadNotIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNotIn(FieldDownload, vs...))
}

// DownloadGT applies the GT predicate on the "download" field.
func DownloadGT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGT(FieldDownload, v))
}

// DownloadGTE applies the GTE predicate on the "download" field.
func DownloadGTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGTE(FieldDownload, v))
}

// DownloadLT applies the LT predicate on the "download" field.
func DownloadLT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLT(FieldDownload, v))
}

// DownloadLTE applies the LTE predicate on the "download" field.
func DownloadLTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLTE(FieldDownload, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v int64) predicate.Cursor {
	return predicate.Cursor(sql.FieldLTE(FieldObservedAt, v))
}

// ClosedEQ applies the EQ predicate on the "closed" field.
func ClosedEQ(v bool) predicate.Cursor {
	return predicate.Cursor(sql.FieldEQ(FieldClosed, v))
}

// ClosedNEQ applies the NEQ predicate on the "closed" field.
func ClosedNEQ(v bool) predicate.Cursor {
	return predicate.Cursor(sql.FieldNEQ(FieldClosed, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cursor) predicate.Cursor {
	return predicate.Cursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cursor) predicate.Cursor {
	return predicate.Cursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cursor) predicate.Cursor {
	return predicate.Cursor(sql.NotPredicates(p))
}
