// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BatchesColumns holds the columns for the "batches" table.
	BatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "stream_id", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "payload_hash", Type: field.TypeString},
	}
	// BatchesTable holds the schema information for the "batches" table.
	BatchesTable = &schema.Table{
		Name:       "batches",
		Columns:    BatchesColumns,
		PrimaryKey: []*schema.Column{BatchesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "batch_stream_id_seq",
				Unique:  true,
				Columns: []*schema.Column{BatchesColumns[2], BatchesColumns[1]},
			},
		},
	}
	// CoresColumns holds the columns for the "cores" table.
	CoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "policy_floor", Type: field.TypeInt64, Default: 0},
		{Name: "authorization", Type: field.TypeBytes, Nullable: true},
		{Name: "applied_revision", Type: field.TypeString, Default: ""},
		{Name: "applied_policy", Type: field.TypeInt64, Default: 0},
		{Name: "applied_config", Type: field.TypeBytes, Nullable: true},
		{Name: "stage", Type: field.TypeString, Default: "idle"},
		{Name: "pending_task", Type: field.TypeString, Default: ""},
		{Name: "pending_revision", Type: field.TypeString, Default: ""},
		{Name: "pending_policy", Type: field.TypeInt64, Default: 0},
		{Name: "pending_config", Type: field.TypeBytes, Nullable: true},
	}
	// CoresTable holds the schema information for the "cores" table.
	CoresTable = &schema.Table{
		Name:       "cores",
		Columns:    CoresColumns,
		PrimaryKey: []*schema.Column{CoresColumns[0]},
	}
	// CursorsColumns holds the columns for the "cursors" table.
	CursorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "runtime_id", Type: field.TypeString},
		{Name: "upload", Type: field.TypeInt64},
		{Name: "download", Type: field.TypeInt64},
		{Name: "observed_at", Type: field.TypeInt64},
		{Name: "closed", Type: field.TypeBool, Default: false},
	}
	// CursorsTable holds the schema information for the "cursors" table.
	CursorsTable = &schema.Table{
		Name:       "cursors",
		Columns:    CursorsColumns,
		PrimaryKey: []*schema.Column{CursorsColumns[0]},
	}
	// StreamsColumns holds the columns for the "streams" table.
	StreamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "next_seq", Type: field.TypeInt64, Default: 1},
		{Name: "committed_seq", Type: field.TypeInt64, Default: 0},
		{Name: "pending_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "recovery_issue", Type: field.TypeString, Default: ""},
	}
	// StreamsTable holds the schema information for the "streams" table.
	StreamsTable = &schema.Table{
		Name:       "streams",
		Columns:    StreamsColumns,
		PrimaryKey: []*schema.Column{StreamsColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "payload_hash", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "binding_epoch", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"accepted", "running", "succeeded", "failed"}, Default: "accepted"},
		{Name: "progress_seq", Type: field.TypeInt64, Default: 0},
		{Name: "result", Type: field.TypeBytes, Nullable: true},
		{Name: "acknowledged", Type: field.TypeBool, Default: false},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BatchesTable,
		CoresTable,
		CursorsTable,
		StreamsTable,
		TasksTable,
	}
)

func init() {
}
