// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Batch is the predicate function for batch builders.
type Batch func(*sql.Selector)

// Core is the predicate function for core builders.
type Core func(*sql.Selector)

// Cursor is the predicate function for cursor builders.
type Cursor func(*sql.Selector)

// Stream is the predicate function for stream builders.
type Stream func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
