// Code generated by ent, DO NOT EDIT.

package task

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPayloadHash holds the string denoting the payload_hash field in the database.
	FieldPayloadHash = "payload_hash"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldBindingEpoch holds the string denoting the binding_epoch field in the database.
	FieldBindingEpoch = "binding_epoch"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProgressSeq holds the string denoting the progress_seq field in the database.
	FieldProgressSeq = "progress_seq"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldAcknowledged holds the string denoting the acknowledged field in the database.
	FieldAcknowledged = "acknowledged"
	// Table holds the table name of the task in the database.
	Table = "tasks"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldPayloadHash,
	FieldKind,
	FieldPayload,
	FieldBindingEpoch,
	FieldStatus,
	FieldProgressSeq,
	FieldResult,
	FieldAcknowledged,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	PayloadHashValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// BindingEpochValidator is a validator for the "binding_epoch" field. It is called by the builders before save.
	BindingEpochValidator func(int64) error
	// DefaultProgressSeq holds the default value on creation for the "progress_seq" field.
	DefaultProgressSeq int64
	// ProgressSeqValidator is a validator for the "progress_seq" field. It is called by the builders before save.
	ProgressSeqValidator func(int64) error
	// DefaultAcknowledged holds the default value on creation for the "acknowledged" field.
	DefaultAcknowledged bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAccepted is the default value of the Status enum.
const DefaultStatus = StatusAccepted

// Status values.
const (
	StatusAccepted  Status = "accepted"
	StatusRunning   Status = "running"
	StatusSucceeded Status = "succeeded"
	StatusFailed    Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAccepted, StatusRunning, StatusSucceeded, StatusFailed:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPayloadHash orders the results by the payload_hash field.
func ByPayloadHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadHash, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByBindingEpoch orders the results by the binding_epoch field.
func ByBindingEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindingEpoch, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProgressSeq orders the results by the progress_seq field.
func ByProgressSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgressSeq, opts...).ToFunc()
}

// ByAcknowledged orders the results by the acknowledged field.
func ByAcknowledged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcknowledged, opts...).ToFunc()
}
