// Code generated by ent, DO NOT EDIT.

package task

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldID, id))
}

// PayloadHash applies equality check predicate on the "payload_hash" field. It's identical to PayloadHashEQ.
func PayloadHash(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPayloadHash, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldKind, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v []byte) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPayload, v))
}

// BindingEpoch applies equality check predicate on the "binding_epoch" field. It's identical to BindingEpochEQ.
func BindingEpoch(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldBindingEpoch, v))
}

// ProgressSeq applies equality check predicate on the "progress_seq" field. It's identical to ProgressSeqEQ.
func ProgressSeq(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProgressSeq, v))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v []byte) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldResult, v))
}

// Acknowledged applies equality check predicate on the "acknowledged" field. It's identical to AcknowledgedEQ.
func Acknowledged(v bool) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAcknowledged, v))
}

// PayloadHashEQ applies the EQ predicate on the "payload_hash" field.
func PayloadHashEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPayloadHash, v))
}

// PayloadHashNEQ applies the NEQ predicate on the "payload_hash" field.
func PayloadHashNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPayloadHash, v))
}

// PayloadHashIn applies the In predicate on the "payload_hash" field.
func PayloadHashIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPayloadHash, vs...))
}

// PayloadHashNotIn applies the NotIn predicate on the "payload_hash" field.
func PayloadHashNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPayloadHash, vs...))
}

// PayloadHashGT applies the GT predicate on the "payload_hash" field.
func PayloadHashGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPayloadHash, v))
}

// PayloadHashGTE applies the GTE predicate on the "payload_hash" field.
func PayloadHashGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPayloadHash, v))
}

// PayloadHashLT applies the LT predicate on the "payload_hash" field.
func PayloadHashLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPayloadHash, v))
}

// PayloadHashLTE applies the LTE predicate on the "payload_hash" field.
func PayloadHashLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPayloadHash, v))
}

// PayloadHashContains applies the Contains predicate on the "payload_hash" field.
func PayloadHashContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldPayloadHash, v))
}

// PayloadHashHasPrefix applies the HasPrefix predicate on the "payload_hash" field.
func PayloadHashHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldPayloadHash, v))
}

// PayloadHashHasSuffix applies the HasSuffix predicate on the "payload_hash" field.
func PayloadHashHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldPayloadHash, v))
}

// PayloadHashEqualFold applies the EqualFold predicate on the "payload_hash" field.
func PayloadHashEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldPayloadHash, v))
}

// PayloadHashContainsFold applies the ContainsFold predicate on the "payload_hash" field.
func PayloadHashContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldPayloadHash, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldKind, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v []byte) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v []byte) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...[]byte) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...[]byte) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v []byte) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v []byte) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v []byte) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v []byte) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPayload, v))
}

// BindingEpochEQ applies the EQ predicate on the "binding_epoch" field.
func BindingEpochEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldBindingEpoch, v))
}

// BindingEpochNEQ applies the NEQ predicate on the "binding_epoch" field.
func BindingEpochNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldBindingEpoch, v))
}

// BindingEpochIn applies the In predicate on the "binding_epoch" field.
func BindingEpochIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldBindingEpoch, vs...))
}

// BindingEpochNotIn applies the NotIn predicate on the "binding_epoch" field.
func BindingEpochNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldBindingEpoch, vs...))
}

// BindingEpochGT applies the GT predicate on the "binding_epoch" field.
func BindingEpochGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldBindingEpoch, v))
}

// BindingEpochGTE applies the GTE predicate on the "binding_epoch" field.
func BindingEpochGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldBindingEpoch, v))
}

// BindingEpochLT applies the LT predicate on the "binding_epoch" field.
func BindingEpochLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldBindingEpoch, v))
}

// BindingEpochLTE applies the LTE predicate on the "binding_epoch" field.
func BindingEpochLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldBindingEpoch, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStatus, vs...))
}

// ProgressSeqEQ applies the EQ predicate on the "progress_seq" field.
func ProgressSeqEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProgressSeq, v))
}

// ProgressSeqNEQ applies the NEQ predicate on the "progress_seq" field.
func ProgressSeqNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldProgressSeq, v))
}

// ProgressSeqIn applies the In predicate on the "progress_seq" field.
func ProgressSeqIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldProgressSeq, vs...))
}

// ProgressSeqNotIn applies the NotIn predicate on the "progress_seq" field.
func ProgressSeqNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldProgressSeq, vs...))
}

// ProgressSeqGT applies the GT predicate on the "progress_seq" field.
func ProgressSeqGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldProgressSeq, v))
}

// ProgressSeqGTE applies the GTE predicate on the "progress_seq" field.
func ProgressSeqGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldProgressSeq, v))
}

// ProgressSeqLT applies the LT predicate on the "progress_seq" field.
func ProgressSeqLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldProgressSeq, v))
}

// ProgressSeqLTE applies the LTE predicate on the "progress_seq" field.
func ProgressSeqLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldProgressSeq, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v []byte) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v []byte) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...[]byte) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...[]byte) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldResult, vs...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v []byte) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldResult, v))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v []byte) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldResult, v))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v []byte) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldResult, v))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v []byte) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldResult, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldResult))
}

// AcknowledgedEQ applies the EQ predicate on the "acknowledged" field.
func AcknowledgedEQ(v bool) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAcknowledged, v))
}

// AcknowledgedNEQ applies the NEQ predicate on the "acknowledged" field.
func AcknowledgedNEQ(v bool) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAcknowledged, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
