// Code generated by ent, DO NOT EDIT.

package batch

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the batch type in the database.
	Label = "batch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldStreamID holds the string denoting the stream_id field in the database.
	FieldStreamID = "stream_id"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldPayloadHash holds the string denoting the payload_hash field in the database.
	FieldPayloadHash = "payload_hash"
	// Table holds the table name of the batch in the database.
	Table = "batches"
)

// Columns holds all SQL columns for batch fields.
var Columns = []string{
	FieldID,
	FieldSeq,
	FieldStreamID,
	FieldSizeBytes,
	FieldPayload,
	FieldPayloadHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	SeqValidator func(int64) error
	// StreamIDValidator is a validator for the "stream_id" field. It is called by the builders before save.
	StreamIDValidator func(string) error
	// DefaultSizeBytes holds the default value on creation for the "size_bytes" field.
	DefaultSizeBytes int64
	// SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	SizeBytesValidator func(int64) error
	// PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	PayloadHashValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Batch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByStreamID orders the results by the stream_id field.
func ByStreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamID, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// ByPayloadHash orders the results by the payload_hash field.
func ByPayloadHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadHash, opts...).ToFunc()
}
