// Code generated by ent, DO NOT EDIT.

package batch

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Batch {
	return predicate.Batch(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Batch {
	return predicate.Batch(sql.FieldContainsFold(FieldID, id))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldSeq, v))
}

// StreamID applies equality check predicate on the "stream_id" field. It's identical to StreamIDEQ.
func StreamID(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldStreamID, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldSizeBytes, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldPayload, v))
}

// PayloadHash applies equality check predicate on the "payload_hash" field. It's identical to PayloadHashEQ.
func PayloadHash(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldPayloadHash, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int64) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int64) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldSeq, v))
}

// StreamIDEQ applies the EQ predicate on the "stream_id" field.
func StreamIDEQ(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldStreamID, v))
}

// StreamIDNEQ applies the NEQ predicate on the "stream_id" field.
func StreamIDNEQ(v string) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldStreamID, v))
}

// StreamIDIn applies the In predicate on the "stream_id" field.
func StreamIDIn(vs ...string) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldStreamID, vs...))
}

// StreamIDNotIn applies the NotIn predicate on the "stream_id" field.
func StreamIDNotIn(vs ...string) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldStreamID, vs...))
}

// StreamIDGT applies the GT predicate on the "stream_id" field.
func StreamIDGT(v string) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldStreamID, v))
}

// StreamIDGTE applies the GTE predicate on the "stream_id" field.
func StreamIDGTE(v string) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldStreamID, v))
}

// StreamIDLT applies the LT predicate on the "stream_id" field.
func StreamIDLT(v string) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldStreamID, v))
}

// StreamIDLTE applies the LTE predicate on the "stream_id" field.
func StreamIDLTE(v string) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldStreamID, v))
}

// StreamIDContains applies the Contains predicate on the "stream_id" field.
func StreamIDContains(v string) predicate.Batch {
	return predicate.Batch(sql.FieldContains(FieldStreamID, v))
}

// StreamIDHasPrefix applies the HasPrefix predicate on the "stream_id" field.
func StreamIDHasPrefix(v string) predicate.Batch {
	return predicate.Batch(sql.FieldHasPrefix(FieldStreamID, v))
}

// StreamIDHasSuffix applies the HasSuffix predicate on the "stream_id" field.
func StreamIDHasSuffix(v string) predicate.Batch {
	return predicate.Batch(sql.FieldHasSuffix(FieldStreamID, v))
}

// StreamIDEqualFold applies the EqualFold predicate on the "stream_id" field.
func StreamIDEqualFold(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEqualFold(FieldStreamID, v))
}

// StreamIDContainsFold applies the ContainsFold predicate on the "stream_id" field.
func StreamIDContainsFold(v string) predicate.Batch {
	return predicate.Batch(sql.FieldContainsFold(FieldStreamID, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldSizeBytes, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...[]byte) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...[]byte) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v []byte) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldPayload, v))
}

// PayloadHashEQ applies the EQ predicate on the "payload_hash" field.
func PayloadHashEQ(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEQ(FieldPayloadHash, v))
}

// PayloadHashNEQ applies the NEQ predicate on the "payload_hash" field.
func PayloadHashNEQ(v string) predicate.Batch {
	return predicate.Batch(sql.FieldNEQ(FieldPayloadHash, v))
}

// PayloadHashIn applies the In predicate on the "payload_hash" field.
func PayloadHashIn(vs ...string) predicate.Batch {
	return predicate.Batch(sql.FieldIn(FieldPayloadHash, vs...))
}

// PayloadHashNotIn applies the NotIn predicate on the "payload_hash" field.
func PayloadHashNotIn(vs ...string) predicate.Batch {
	return predicate.Batch(sql.FieldNotIn(FieldPayloadHash, vs...))
}

// PayloadHashGT applies the GT predicate on the "payload_hash" field.
func PayloadHashGT(v string) predicate.Batch {
	return predicate.Batch(sql.FieldGT(FieldPayloadHash, v))
}

// PayloadHashGTE applies the GTE predicate on the "payload_hash" field.
func PayloadHashGTE(v string) predicate.Batch {
	return predicate.Batch(sql.FieldGTE(FieldPayloadHash, v))
}

// PayloadHashLT applies the LT predicate on the "payload_hash" field.
func PayloadHashLT(v string) predicate.Batch {
	return predicate.Batch(sql.FieldLT(FieldPayloadHash, v))
}

// PayloadHashLTE applies the LTE predicate on the "payload_hash" field.
func PayloadHashLTE(v string) predicate.Batch {
	return predicate.Batch(sql.FieldLTE(FieldPayloadHash, v))
}

// PayloadHashContains applies the Contains predicate on the "payload_hash" field.
func PayloadHashContains(v string) predicate.Batch {
	return predicate.Batch(sql.FieldContains(FieldPayloadHash, v))
}

// PayloadHashHasPrefix applies the HasPrefix predicate on the "payload_hash" field.
func PayloadHashHasPrefix(v string) predicate.Batch {
	return predicate.Batch(sql.FieldHasPrefix(FieldPayloadHash, v))
}

// PayloadHashHasSuffix applies the HasSuffix predicate on the "payload_hash" field.
func PayloadHashHasSuffix(v string) predicate.Batch {
	return predicate.Batch(sql.FieldHasSuffix(FieldPayloadHash, v))
}

// PayloadHashEqualFold applies the EqualFold predicate on the "payload_hash" field.
func PayloadHashEqualFold(v string) predicate.Batch {
	return predicate.Batch(sql.FieldEqualFold(FieldPayloadHash, v))
}

// PayloadHashContainsFold applies the ContainsFold predicate on the "payload_hash" field.
func PayloadHashContainsFold(v string) predicate.Batch {
	return predicate.Batch(sql.FieldContainsFold(FieldPayloadHash, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Batch) predicate.Batch {
	return predicate.Batch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Batch) predicate.Batch {
	return predicate.Batch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Batch) predicate.Batch {
	return predicate.Batch(sql.NotPredicates(p))
}
