// Code generated by ent, DO NOT EDIT.

package stream

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the stream type in the database.
	Label = "stream"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNextSeq holds the string denoting the next_seq field in the database.
	FieldNextSeq = "next_seq"
	// FieldCommittedSeq holds the string denoting the committed_seq field in the database.
	FieldCommittedSeq = "committed_seq"
	// FieldPendingBytes holds the string denoting the pending_bytes field in the database.
	FieldPendingBytes = "pending_bytes"
	// FieldRecoveryIssue holds the string denoting the recovery_issue field in the database.
	FieldRecoveryIssue = "recovery_issue"
	// Table holds the table name of the stream in the database.
	Table = "streams"
)

// Columns holds all SQL columns for stream fields.
var Columns = []string{
	FieldID,
	FieldNextSeq,
	FieldCommittedSeq,
	FieldPendingBytes,
	FieldRecoveryIssue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNextSeq holds the default value on creation for the "next_seq" field.
	DefaultNextSeq int64
	// NextSeqValidator is a validator for the "next_seq" field. It is called by the builders before save.
	NextSeqValidator func(int64) error
	// DefaultCommittedSeq holds the default value on creation for the "committed_seq" field.
	DefaultCommittedSeq int64
	// CommittedSeqValidator is a validator for the "committed_seq" field. It is called by the builders before save.
	CommittedSeqValidator func(int64) error
	// DefaultPendingBytes holds the default value on creation for the "pending_bytes" field.
	DefaultPendingBytes int64
	// PendingBytesValidator is a validator for the "pending_bytes" field. It is called by the builders before save.
	PendingBytesValidator func(int64) error
	// DefaultRecoveryIssue holds the default value on creation for the "recovery_issue" field.
	DefaultRecoveryIssue string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Stream queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNextSeq orders the results by the next_seq field.
func ByNextSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextSeq, opts...).ToFunc()
}

// ByCommittedSeq orders the results by the committed_seq field.
func ByCommittedSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommittedSeq, opts...).ToFunc()
}

// ByPendingBytes orders the results by the pending_bytes field.
func ByPendingBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingBytes, opts...).ToFunc()
}

// ByRecoveryIssue orders the results by the recovery_issue field.
func ByRecoveryIssue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecoveryIssue, opts...).ToFunc()
}
