// Code generated by ent, DO NOT EDIT.

package stream

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldID, id))
}

// NextSeq applies equality check predicate on the "next_seq" field. It's identical to NextSeqEQ.
func NextSeq(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldNextSeq, v))
}

// CommittedSeq applies equality check predicate on the "committed_seq" field. It's identical to CommittedSeqEQ.
func CommittedSeq(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldCommittedSeq, v))
}

// PendingBytes applies equality check predicate on the "pending_bytes" field. It's identical to PendingBytesEQ.
func PendingBytes(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldPendingBytes, v))
}

// RecoveryIssue applies equality check predicate on the "recovery_issue" field. It's identical to RecoveryIssueEQ.
func RecoveryIssue(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldRecoveryIssue, v))
}

// NextSeqEQ applies the EQ predicate on the "next_seq" field.
func NextSeqEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldNextSeq, v))
}

// NextSeqNEQ applies the NEQ predicate on the "next_seq" field.
func NextSeqNEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldNextSeq, v))
}

// NextSeqIn applies the In predicate on the "next_seq" field.
func NextSeqIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldNextSeq, vs...))
}

// NextSeqNotIn applies the NotIn predicate on the "next_seq" field.
func NextSeqNotIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldNextSeq, vs...))
}

// NextSeqGT applies the GT predicate on the "next_seq" field.
func NextSeqGT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldNextSeq, v))
}

// NextSeqGTE applies the GTE predicate on the "next_seq" field.
func NextSeqGTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldNextSeq, v))
}

// NextSeqLT applies the LT predicate on the "next_seq" field.
func NextSeqLT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldNextSeq, v))
}

// NextSeqLTE applies the LTE predicate on the "next_seq" field.
func NextSeqLTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldNextSeq, v))
}

// CommittedSeqEQ applies the EQ predicate on the "committed_seq" field.
func CommittedSeqEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldCommittedSeq, v))
}

// CommittedSeqNEQ applies the NEQ predicate on the "committed_seq" field.
func CommittedSeqNEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldCommittedSeq, v))
}

// CommittedSeqIn applies the In predicate on the "committed_seq" field.
func CommittedSeqIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldCommittedSeq, vs...))
}

// CommittedSeqNotIn applies the NotIn predicate on the "committed_seq" field.
func CommittedSeqNotIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldCommittedSeq, vs...))
}

// CommittedSeqGT applies the GT predicate on the "committed_seq" field.
func CommittedSeqGT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldCommittedSeq, v))
}

// CommittedSeqGTE applies the GTE predicate on the "committed_seq" field.
func CommittedSeqGTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldCommittedSeq, v))
}

// CommittedSeqLT applies the LT predicate on the "committed_seq" field.
func CommittedSeqLT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldCommittedSeq, v))
}

// CommittedSeqLTE applies the LTE predicate on the "committed_seq" field.
func CommittedSeqLTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldCommittedSeq, v))
}

// PendingBytesEQ applies the EQ predicate on the "pending_bytes" field.
func PendingBytesEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldPendingBytes, v))
}

// PendingBytesNEQ applies the NEQ predicate on the "pending_bytes" field.
func PendingBytesNEQ(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldPendingBytes, v))
}

// PendingBytesIn applies the In predicate on the "pending_bytes" field.
func PendingBytesIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldPendingBytes, vs...))
}

// PendingBytesNotIn applies the NotIn predicate on the "pending_bytes" field.
func PendingBytesNotIn(vs ...int64) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldPendingBytes, vs...))
}

// PendingBytesGT applies the GT predicate on the "pending_bytes" field.
func PendingBytesGT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldPendingBytes, v))
}

// PendingBytesGTE applies the GTE predicate on the "pending_bytes" field.
func PendingBytesGTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldPendingBytes, v))
}

// PendingBytesLT applies the LT predicate on the "pending_bytes" field.
func PendingBytesLT(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldPendingBytes, v))
}

// PendingBytesLTE applies the LTE predicate on the "pending_bytes" field.
func PendingBytesLTE(v int64) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldPendingBytes, v))
}

// RecoveryIssueEQ applies the EQ predicate on the "recovery_issue" field.
func RecoveryIssueEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldRecoveryIssue, v))
}

// RecoveryIssueNEQ applies the NEQ predicate on the "recovery_issue" field.
func RecoveryIssueNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldRecoveryIssue, v))
}

// RecoveryIssueIn applies the In predicate on the "recovery_issue" field.
func RecoveryIssueIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldRecoveryIssue, vs...))
}

// RecoveryIssueNotIn applies the NotIn predicate on the "recovery_issue" field.
func RecoveryIssueNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldRecoveryIssue, vs...))
}

// RecoveryIssueGT applies the GT predicate on the "recovery_issue" field.
func RecoveryIssueGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldRecoveryIssue, v))
}

// RecoveryIssueGTE applies the GTE predicate on the "recovery_issue" field.
func RecoveryIssueGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldRecoveryIssue, v))
}

// RecoveryIssueLT applies the LT predicate on the "recovery_issue" field.
func RecoveryIssueLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldRecoveryIssue, v))
}

// RecoveryIssueLTE applies the LTE predicate on the "recovery_issue" field.
func RecoveryIssueLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldRecoveryIssue, v))
}

// RecoveryIssueContains applies the Contains predicate on the "recovery_issue" field.
func RecoveryIssueContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldRecoveryIssue, v))
}

// RecoveryIssueHasPrefix applies the HasPrefix predicate on the "recovery_issue" field.
func RecoveryIssueHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldRecoveryIssue, v))
}

// RecoveryIssueHasSuffix applies the HasSuffix predicate on the "recovery_issue" field.
func RecoveryIssueHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldRecoveryIssue, v))
}

// RecoveryIssueEqualFold applies the EqualFold predicate on the "recovery_issue" field.
func RecoveryIssueEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldRecoveryIssue, v))
}

// RecoveryIssueContainsFold applies the ContainsFold predicate on the "recovery_issue" field.
func RecoveryIssueContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldRecoveryIssue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.NotPredicates(p))
}
