// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/batch"
)

// Batch is the model entity for the Batch schema.
type Batch struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Seq holds the value of the "seq" field.
	Seq int64 `json:"seq,omitempty"`
	// StreamID holds the value of the "stream_id" field.
	StreamID string `json:"stream_id,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// PayloadHash holds the value of the "payload_hash" field.
	PayloadHash  string `json:"payload_hash,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Batch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case batch.FieldPayload:
			values[i] = new([]byte)
		case batch.FieldSeq, batch.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case batch.FieldID, batch.FieldStreamID, batch.FieldPayloadHash:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Batch fields.
func (_m *Batch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case batch.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case batch.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = value.Int64
			}
		case batch.FieldStreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_id", values[i])
			} else if value.Valid {
				_m.StreamID = value.String
			}
		case batch.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case batch.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				_m.Payload = *value
			}
		case batch.FieldPayloadHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_hash", values[i])
			} else if value.Valid {
				_m.PayloadHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Batch.
// This includes values selected through modifiers, order, etc.
func (_m *Batch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Batch.
// Note that you need to call Batch.Unwrap() before calling this method if this Batch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Batch) Update() *BatchUpdateOne {
	return NewBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Batch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Batch) Unwrap() *Batch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Batch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Batch) String() string {
	var builder strings.Builder
	builder.WriteString("Batch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("stream_id=")
	builder.WriteString(_m.StreamID)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("payload_hash=")
	builder.WriteString(_m.PayloadHash)
	builder.WriteByte(')')
	return builder.String()
}

// Batches is a parsable slice of Batch.
type Batches []*Batch
