// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/batch"
)

// BatchCreate is the builder for creating a Batch entity.
type BatchCreate struct {
	config
	mutation *BatchMutation
	hooks    []Hook
}

// SetSeq sets the "seq" field.
func (_c *BatchCreate) SetSeq(v int64) *BatchCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetStreamID sets the "stream_id" field.
func (_c *BatchCreate) SetStreamID(v string) *BatchCreate {
	_c.mutation.SetStreamID(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *BatchCreate) SetSizeBytes(v int64) *BatchCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *BatchCreate) SetNillableSizeBytes(v *int64) *BatchCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *BatchCreate) SetPayload(v []byte) *BatchCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetPayloadHash sets the "payload_hash" field.
func (_c *BatchCreate) SetPayloadHash(v string) *BatchCreate {
	_c.mutation.SetPayloadHash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BatchCreate) SetID(v string) *BatchCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BatchMutation object of the builder.
func (_c *BatchCreate) Mutation() *BatchMutation {
	return _c.mutation
}

// Save creates the Batch in the database.
func (_c *BatchCreate) Save(ctx context.Context) (*Batch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BatchCreate) SaveX(ctx context.Context) *Batch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BatchCreate) defaults() {
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := batch.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BatchCreate) check() error {
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "Batch.seq"`)}
	}
	if v, ok := _c.mutation.Seq(); ok {
		if err := batch.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "Batch.seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamID(); !ok {
		return &ValidationError{Name: "stream_id", err: errors.New(`ent: missing required field "Batch.stream_id"`)}
	}
	if v, ok := _c.mutation.StreamID(); ok {
		if err := batch.StreamIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_id", err: fmt.Errorf(`ent: validator failed for field "Batch.stream_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Batch.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := batch.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "Batch.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Batch.payload"`)}
	}
	if _, ok := _c.mutation.PayloadHash(); !ok {
		return &ValidationError{Name: "payload_hash", err: errors.New(`ent: missing required field "Batch.payload_hash"`)}
	}
	if v, ok := _c.mutation.PayloadHash(); ok {
		if err := batch.PayloadHashValidator(v); err != nil {
			return &ValidationError{Name: "payload_hash", err: fmt.Errorf(`ent: validator failed for field "Batch.payload_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := batch.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Batch.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BatchCreate) sqlSave(ctx context.Context) (*Batch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Batch.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BatchCreate) createSpec() (*Batch, *sqlgraph.CreateSpec) {
	var (
		_node = &Batch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(batch.Table, sqlgraph.NewFieldSpec(batch.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(batch.FieldSeq, field.TypeInt64, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.StreamID(); ok {
		_spec.SetField(batch.FieldStreamID, field.TypeString, value)
		_node.StreamID = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(batch.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(batch.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.PayloadHash(); ok {
		_spec.SetField(batch.FieldPayloadHash, field.TypeString, value)
		_node.PayloadHash = value
	}
	return _node, _spec
}

// BatchCreateBulk is the builder for creating many Batch entities in bulk.
type BatchCreateBulk struct {
	config
	err      error
	builders []*BatchCreate
}

// Save creates the Batch entities in the database.
func (_c *BatchCreateBulk) Save(ctx context.Context) ([]*Batch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Batch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BatchCreateBulk) SaveX(ctx context.Context) []*Batch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
