// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/batch"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/core"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/cursor"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/stream"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/task"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Batch is the client for interacting with the Batch builders.
	Batch *BatchClient
	// Core is the client for interacting with the Core builders.
	Core *CoreClient
	// Cursor is the client for interacting with the Cursor builders.
	Cursor *CursorClient
	// Stream is the client for interacting with the Stream builders.
	Stream *StreamClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Batch = NewBatchClient(c.config)
	c.Core = NewCoreClient(c.config)
	c.Cursor = NewCursorClient(c.config)
	c.Stream = NewStreamClient(c.config)
	c.Task = NewTaskClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Batch:  NewBatchClient(cfg),
		Core:   NewCoreClient(cfg),
		Cursor: NewCursorClient(cfg),
		Stream: NewStreamClient(cfg),
		Task:   NewTaskClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Batch:  NewBatchClient(cfg),
		Core:   NewCoreClient(cfg),
		Cursor: NewCursorClient(cfg),
		Stream: NewStreamClient(cfg),
		Task:   NewTaskClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Batch.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Batch.Use(hooks...)
	c.Core.Use(hooks...)
	c.Cursor.Use(hooks...)
	c.Stream.Use(hooks...)
	c.Task.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Batch.Intercept(interceptors...)
	c.Core.Intercept(interceptors...)
	c.Cursor.Intercept(interceptors...)
	c.Stream.Intercept(interceptors...)
	c.Task.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BatchMutation:
		return c.Batch.mutate(ctx, m)
	case *CoreMutation:
		return c.Core.mutate(ctx, m)
	case *CursorMutation:
		return c.Cursor.mutate(ctx, m)
	case *StreamMutation:
		return c.Stream.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BatchClient is a client for the Batch schema.
type BatchClient struct {
	config
}

// NewBatchClient returns a client for the Batch from the given config.
func NewBatchClient(c config) *BatchClient {
	return &BatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `batch.Hooks(f(g(h())))`.
func (c *BatchClient) Use(hooks ...Hook) {
	c.hooks.Batch = append(c.hooks.Batch, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `batch.Intercept(f(g(h())))`.
func (c *BatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.Batch = append(c.inters.Batch, interceptors...)
}

// Create returns a builder for creating a Batch entity.
func (c *BatchClient) Create() *BatchCreate {
	mutation := newBatchMutation(c.config, OpCreate)
	return &BatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Batch entities.
func (c *BatchClient) CreateBulk(builders ...*BatchCreate) *BatchCreateBulk {
	return &BatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BatchClient) MapCreateBulk(slice any, setFunc func(*BatchCreate, int)) *BatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BatchCreateBulk{err: fmt.Errorf("calling to BatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Batch.
func (c *BatchClient) Update() *BatchUpdate {
	mutation := newBatchMutation(c.config, OpUpdate)
	return &BatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BatchClient) UpdateOne(_m *Batch) *BatchUpdateOne {
	mutation := newBatchMutation(c.config, OpUpdateOne, withBatch(_m))
	return &BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BatchClient) UpdateOneID(id string) *BatchUpdateOne {
	mutation := newBatchMutation(c.config, OpUpdateOne, withBatchID(id))
	return &BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Batch.
func (c *BatchClient) Delete() *BatchDelete {
	mutation := newBatchMutation(c.config, OpDelete)
	return &BatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BatchClient) DeleteOne(_m *Batch) *BatchDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BatchClient) DeleteOneID(id string) *BatchDeleteOne {
	builder := c.Delete().Where(batch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BatchDeleteOne{builder}
}

// Query returns a query builder for Batch.
func (c *BatchClient) Query() *BatchQuery {
	return &BatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBatch},
		inters: c.Interceptors(),
	}
}

// Get returns a Batch entity by its id.
func (c *BatchClient) Get(ctx context.Context, id string) (*Batch, error) {
	return c.Query().Where(batch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BatchClient) GetX(ctx context.Context, id string) *Batch {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BatchClient) Hooks() []Hook {
	return c.hooks.Batch
}

// Interceptors returns the client interceptors.
func (c *BatchClient) Interceptors() []Interceptor {
	return c.inters.Batch
}

func (c *BatchClient) mutate(ctx context.Context, m *BatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Batch mutation op: %q", m.Op())
	}
}

// CoreClient is a client for the Core schema.
type CoreClient struct {
	config
}

// NewCoreClient returns a client for the Core from the given config.
func NewCoreClient(c config) *CoreClient {
	return &CoreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `core.Hooks(f(g(h())))`.
func (c *CoreClient) Use(hooks ...Hook) {
	c.hooks.Core = append(c.hooks.Core, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `core.Intercept(f(g(h())))`.
func (c *CoreClient) Intercept(interceptors ...Interceptor) {
	c.inters.Core = append(c.inters.Core, interceptors...)
}

// Create returns a builder for creating a Core entity.
func (c *CoreClient) Create() *CoreCreate {
	mutation := newCoreMutation(c.config, OpCreate)
	return &CoreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Core entities.
func (c *CoreClient) CreateBulk(builders ...*CoreCreate) *CoreCreateBulk {
	return &CoreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CoreClient) MapCreateBulk(slice any, setFunc func(*CoreCreate, int)) *CoreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CoreCreateBulk{err: fmt.Errorf("calling to CoreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CoreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CoreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Core.
func (c *CoreClient) Update() *CoreUpdate {
	mutation := newCoreMutation(c.config, OpUpdate)
	return &CoreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CoreClient) UpdateOne(_m *Core) *CoreUpdateOne {
	mutation := newCoreMutation(c.config, OpUpdateOne, withCore(_m))
	return &CoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CoreClient) UpdateOneID(id string) *CoreUpdateOne {
	mutation := newCoreMutation(c.config, OpUpdateOne, withCoreID(id))
	return &CoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Core.
func (c *CoreClient) Delete() *CoreDelete {
	mutation := newCoreMutation(c.config, OpDelete)
	return &CoreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CoreClient) DeleteOne(_m *Core) *CoreDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CoreClient) DeleteOneID(id string) *CoreDeleteOne {
	builder := c.Delete().Where(core.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CoreDeleteOne{builder}
}

// Query returns a query builder for Core.
func (c *CoreClient) Query() *CoreQuery {
	return &CoreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCore},
		inters: c.Interceptors(),
	}
}

// Get returns a Core entity by its id.
func (c *CoreClient) Get(ctx context.Context, id string) (*Core, error) {
	return c.Query().Where(core.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CoreClient) GetX(ctx context.Context, id string) *Core {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CoreClient) Hooks() []Hook {
	return c.hooks.Core
}

// Interceptors returns the client interceptors.
func (c *CoreClient) Interceptors() []Interceptor {
	return c.inters.Core
}

func (c *CoreClient) mutate(ctx context.Context, m *CoreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CoreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CoreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CoreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Core mutation op: %q", m.Op())
	}
}

// CursorClient is a client for the Cursor schema.
type CursorClient struct {
	config
}

// NewCursorClient returns a client for the Cursor from the given config.
func NewCursorClient(c config) *CursorClient {
	return &CursorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cursor.Hooks(f(g(h())))`.
func (c *CursorClient) Use(hooks ...Hook) {
	c.hooks.Cursor = append(c.hooks.Cursor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cursor.Intercept(f(g(h())))`.
func (c *CursorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Cursor = append(c.inters.Cursor, interceptors...)
}

// Create returns a builder for creating a Cursor entity.
func (c *CursorClient) Create() *CursorCreate {
	mutation := newCursorMutation(c.config, OpCreate)
	return &CursorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Cursor entities.
func (c *CursorClient) CreateBulk(builders ...*CursorCreate) *CursorCreateBulk {
	return &CursorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CursorClient) MapCreateBulk(slice any, setFunc func(*CursorCreate, int)) *CursorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CursorCreateBulk{err: fmt.Errorf("calling to CursorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CursorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CursorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Cursor.
func (c *CursorClient) Update() *CursorUpdate {
	mutation := newCursorMutation(c.config, OpUpdate)
	return &CursorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CursorClient) UpdateOne(_m *Cursor) *CursorUpdateOne {
	mutation := newCursorMutation(c.config, OpUpdateOne, withCursor(_m))
	return &CursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CursorClient) UpdateOneID(id string) *CursorUpdateOne {
	mutation := newCursorMutation(c.config, OpUpdateOne, withCursorID(id))
	return &CursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Cursor.
func (c *CursorClient) Delete() *CursorDelete {
	mutation := newCursorMutation(c.config, OpDelete)
	return &CursorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CursorClient) DeleteOne(_m *Cursor) *CursorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CursorClient) DeleteOneID(id string) *CursorDeleteOne {
	builder := c.Delete().Where(cursor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CursorDeleteOne{builder}
}

// Query returns a query builder for Cursor.
func (c *CursorClient) Query() *CursorQuery {
	return &CursorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCursor},
		inters: c.Interceptors(),
	}
}

// Get returns a Cursor entity by its id.
func (c *CursorClient) Get(ctx context.Context, id string) (*Cursor, error) {
	return c.Query().Where(cursor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CursorClient) GetX(ctx context.Context, id string) *Cursor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CursorClient) Hooks() []Hook {
	return c.hooks.Cursor
}

// Interceptors returns the client interceptors.
func (c *CursorClient) Interceptors() []Interceptor {
	return c.inters.Cursor
}

func (c *CursorClient) mutate(ctx context.Context, m *CursorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CursorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CursorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CursorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Cursor mutation op: %q", m.Op())
	}
}

// StreamClient is a client for the Stream schema.
type StreamClient struct {
	config
}

// NewStreamClient returns a client for the Stream from the given config.
func NewStreamClient(c config) *StreamClient {
	return &StreamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stream.Hooks(f(g(h())))`.
func (c *StreamClient) Use(hooks ...Hook) {
	c.hooks.Stream = append(c.hooks.Stream, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stream.Intercept(f(g(h())))`.
func (c *StreamClient) Intercept(interceptors ...Interceptor) {
	c.inters.Stream = append(c.inters.Stream, interceptors...)
}

// Create returns a builder for creating a Stream entity.
func (c *StreamClient) Create() *StreamCreate {
	mutation := newStreamMutation(c.config, OpCreate)
	return &StreamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Stream entities.
func (c *StreamClient) CreateBulk(builders ...*StreamCreate) *StreamCreateBulk {
	return &StreamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StreamClient) MapCreateBulk(slice any, setFunc func(*StreamCreate, int)) *StreamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StreamCreateBulk{err: fmt.Errorf("calling to StreamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StreamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StreamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Stream.
func (c *StreamClient) Update() *StreamUpdate {
	mutation := newStreamMutation(c.config, OpUpdate)
	return &StreamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StreamClient) UpdateOne(_m *Stream) *StreamUpdateOne {
	mutation := newStreamMutation(c.config, OpUpdateOne, withStream(_m))
	return &StreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StreamClient) UpdateOneID(id string) *StreamUpdateOne {
	mutation := newStreamMutation(c.config, OpUpdateOne, withStreamID(id))
	return &StreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Stream.
func (c *StreamClient) Delete() *StreamDelete {
	mutation := newStreamMutation(c.config, OpDelete)
	return &StreamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StreamClient) DeleteOne(_m *Stream) *StreamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StreamClient) DeleteOneID(id string) *StreamDeleteOne {
	builder := c.Delete().Where(stream.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StreamDeleteOne{builder}
}

// Query returns a query builder for Stream.
func (c *StreamClient) Query() *StreamQuery {
	return &StreamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStream},
		inters: c.Interceptors(),
	}
}

// Get returns a Stream entity by its id.
func (c *StreamClient) Get(ctx context.Context, id string) (*Stream, error) {
	return c.Query().Where(stream.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StreamClient) GetX(ctx context.Context, id string) *Stream {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *StreamClient) Hooks() []Hook {
	return c.hooks.Stream
}

// Interceptors returns the client interceptors.
func (c *StreamClient) Interceptors() []Interceptor {
	return c.inters.Stream
}

func (c *StreamClient) mutate(ctx context.Context, m *StreamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StreamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StreamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StreamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Stream mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id string) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id string) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id string) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id string) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Batch, Core, Cursor, Stream, Task []ent.Hook
	}
	inters struct {
		Batch, Core, Cursor, Stream, Task []ent.Interceptor
	}
)
