// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/core"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// CoreUpdate is the builder for updating Core entities.
type CoreUpdate struct {
	config
	hooks    []Hook
	mutation *CoreMutation
}

// Where appends a list predicates to the CoreUpdate builder.
func (_u *CoreUpdate) Where(ps ...predicate.Core) *CoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPolicyFloor sets the "policy_floor" field.
func (_u *CoreUpdate) SetPolicyFloor(v int64) *CoreUpdate {
	_u.mutation.ResetPolicyFloor()
	_u.mutation.SetPolicyFloor(v)
	return _u
}

// SetNillablePolicyFloor sets the "policy_floor" field if the given value is not nil.
func (_u *CoreUpdate) SetNillablePolicyFloor(v *int64) *CoreUpdate {
	if v != nil {
		_u.SetPolicyFloor(*v)
	}
	return _u
}

// AddPolicyFloor adds value to the "policy_floor" field.
func (_u *CoreUpdate) AddPolicyFloor(v int64) *CoreUpdate {
	_u.mutation.AddPolicyFloor(v)
	return _u
}

// SetAuthorization sets the "authorization" field.
func (_u *CoreUpdate) SetAuthorization(v []byte) *CoreUpdate {
	_u.mutation.SetAuthorization(v)
	return _u
}

// ClearAuthorization clears the value of the "authorization" field.
func (_u *CoreUpdate) ClearAuthorization() *CoreUpdate {
	_u.mutation.ClearAuthorization()
	return _u
}

// SetAppliedRevision sets the "applied_revision" field.
func (_u *CoreUpdate) SetAppliedRevision(v string) *CoreUpdate {
	_u.mutation.SetAppliedRevision(v)
	return _u
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_u *CoreUpdate) SetNillableAppliedRevision(v *string) *CoreUpdate {
	if v != nil {
		_u.SetAppliedRevision(*v)
	}
	return _u
}

// SetAppliedPolicy sets the "applied_policy" field.
func (_u *CoreUpdate) SetAppliedPolicy(v int64) *CoreUpdate {
	_u.mutation.ResetAppliedPolicy()
	_u.mutation.SetAppliedPolicy(v)
	return _u
}

// SetNillableAppliedPolicy sets the "applied_policy" field if the given value is not nil.
func (_u *CoreUpdate) SetNillableAppliedPolicy(v *int64) *CoreUpdate {
	if v != nil {
		_u.SetAppliedPolicy(*v)
	}
	return _u
}

// AddAppliedPolicy adds value to the "applied_policy" field.
func (_u *CoreUpdate) AddAppliedPolicy(v int64) *CoreUpdate {
	_u.mutation.AddAppliedPolicy(v)
	return _u
}

// SetAppliedConfig sets the "applied_config" field.
func (_u *CoreUpdate) SetAppliedConfig(v []byte) *CoreUpdate {
	_u.mutation.SetAppliedConfig(v)
	return _u
}

// ClearAppliedConfig clears the value of the "applied_config" field.
func (_u *CoreUpdate) ClearAppliedConfig() *CoreUpdate {
	_u.mutation.ClearAppliedConfig()
	return _u
}

// SetStage sets the "stage" field.
func (_u *CoreUpdate) SetStage(v string) *CoreUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *CoreUpdate) SetNillableStage(v *string) *CoreUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetPendingTask sets the "pending_task" field.
func (_u *CoreUpdate) SetPendingTask(v string) *CoreUpdate {
	_u.mutation.SetPendingTask(v)
	return _u
}

// SetNillablePendingTask sets the "pending_task" field if the given value is not nil.
func (_u *CoreUpdate) SetNillablePendingTask(v *string) *CoreUpdate {
	if v != nil {
		_u.SetPendingTask(*v)
	}
	return _u
}

// SetPendingRevision sets the "pending_revision" field.
func (_u *CoreUpdate) SetPendingRevision(v string) *CoreUpdate {
	_u.mutation.SetPendingRevision(v)
	return _u
}

// SetNillablePendingRevision sets the "pending_revision" field if the given value is not nil.
func (_u *CoreUpdate) SetNillablePendingRevision(v *string) *CoreUpdate {
	if v != nil {
		_u.SetPendingRevision(*v)
	}
	return _u
}

// SetPendingPolicy sets the "pending_policy" field.
func (_u *CoreUpdate) SetPendingPolicy(v int64) *CoreUpdate {
	_u.mutation.ResetPendingPolicy()
	_u.mutation.SetPendingPolicy(v)
	return _u
}

// SetNillablePendingPolicy sets the "pending_policy" field if the given value is not nil.
func (_u *CoreUpdate) SetNillablePendingPolicy(v *int64) *CoreUpdate {
	if v != nil {
		_u.SetPendingPolicy(*v)
	}
	return _u
}

// AddPendingPolicy adds value to the "pending_policy" field.
func (_u *CoreUpdate) AddPendingPolicy(v int64) *CoreUpdate {
	_u.mutation.AddPendingPolicy(v)
	return _u
}

// SetPendingConfig sets the "pending_config" field.
func (_u *CoreUpdate) SetPendingConfig(v []byte) *CoreUpdate {
	_u.mutation.SetPendingConfig(v)
	return _u
}

// ClearPendingConfig clears the value of the "pending_config" field.
func (_u *CoreUpdate) ClearPendingConfig() *CoreUpdate {
	_u.mutation.ClearPendingConfig()
	return _u
}

// Mutation returns the CoreMutation object of the builder.
func (_u *CoreUpdate) Mutation() *CoreMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoreUpdate) check() error {
	if v, ok := _u.mutation.PolicyFloor(); ok {
		if err := core.PolicyFloorValidator(v); err != nil {
			return &ValidationError{Name: "policy_floor", err: fmt.Errorf(`ent: validator failed for field "Core.policy_floor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppliedPolicy(); ok {
		if err := core.AppliedPolicyValidator(v); err != nil {
			return &ValidationError{Name: "applied_policy", err: fmt.Errorf(`ent: validator failed for field "Core.applied_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingPolicy(); ok {
		if err := core.PendingPolicyValidator(v); err != nil {
			return &ValidationError{Name: "pending_policy", err: fmt.Errorf(`ent: validator failed for field "Core.pending_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *CoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(core.Table, core.Columns, sqlgraph.NewFieldSpec(core.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyFloor(); ok {
		_spec.SetField(core.FieldPolicyFloor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPolicyFloor(); ok {
		_spec.AddField(core.FieldPolicyFloor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Authorization(); ok {
		_spec.SetField(core.FieldAuthorization, field.TypeBytes, value)
	}
	if _u.mutation.AuthorizationCleared() {
		_spec.ClearField(core.FieldAuthorization, field.TypeBytes)
	}
	if value, ok := _u.mutation.AppliedRevision(); ok {
		_spec.SetField(core.FieldAppliedRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliedPolicy(); ok {
		_spec.SetField(core.FieldAppliedPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedPolicy(); ok {
		_spec.AddField(core.FieldAppliedPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedConfig(); ok {
		_spec.SetField(core.FieldAppliedConfig, field.TypeBytes, value)
	}
	if _u.mutation.AppliedConfigCleared() {
		_spec.ClearField(core.FieldAppliedConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(core.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingTask(); ok {
		_spec.SetField(core.FieldPendingTask, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingRevision(); ok {
		_spec.SetField(core.FieldPendingRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingPolicy(); ok {
		_spec.SetField(core.FieldPendingPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingPolicy(); ok {
		_spec.AddField(core.FieldPendingPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingConfig(); ok {
		_spec.SetField(core.FieldPendingConfig, field.TypeBytes, value)
	}
	if _u.mutation.PendingConfigCleared() {
		_spec.ClearField(core.FieldPendingConfig, field.TypeBytes)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{core.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoreUpdateOne is the builder for updating a single Core entity.
type CoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CoreMutation
}

// SetPolicyFloor sets the "policy_floor" field.
func (_u *CoreUpdateOne) SetPolicyFloor(v int64) *CoreUpdateOne {
	_u.mutation.ResetPolicyFloor()
	_u.mutation.SetPolicyFloor(v)
	return _u
}

// SetNillablePolicyFloor sets the "policy_floor" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillablePolicyFloor(v *int64) *CoreUpdateOne {
	if v != nil {
		_u.SetPolicyFloor(*v)
	}
	return _u
}

// AddPolicyFloor adds value to the "policy_floor" field.
func (_u *CoreUpdateOne) AddPolicyFloor(v int64) *CoreUpdateOne {
	_u.mutation.AddPolicyFloor(v)
	return _u
}

// SetAuthorization sets the "authorization" field.
func (_u *CoreUpdateOne) SetAuthorization(v []byte) *CoreUpdateOne {
	_u.mutation.SetAuthorization(v)
	return _u
}

// ClearAuthorization clears the value of the "authorization" field.
func (_u *CoreUpdateOne) ClearAuthorization() *CoreUpdateOne {
	_u.mutation.ClearAuthorization()
	return _u
}

// SetAppliedRevision sets the "applied_revision" field.
func (_u *CoreUpdateOne) SetAppliedRevision(v string) *CoreUpdateOne {
	_u.mutation.SetAppliedRevision(v)
	return _u
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillableAppliedRevision(v *string) *CoreUpdateOne {
	if v != nil {
		_u.SetAppliedRevision(*v)
	}
	return _u
}

// SetAppliedPolicy sets the "applied_policy" field.
func (_u *CoreUpdateOne) SetAppliedPolicy(v int64) *CoreUpdateOne {
	_u.mutation.ResetAppliedPolicy()
	_u.mutation.SetAppliedPolicy(v)
	return _u
}

// SetNillableAppliedPolicy sets the "applied_policy" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillableAppliedPolicy(v *int64) *CoreUpdateOne {
	if v != nil {
		_u.SetAppliedPolicy(*v)
	}
	return _u
}

// AddAppliedPolicy adds value to the "applied_policy" field.
func (_u *CoreUpdateOne) AddAppliedPolicy(v int64) *CoreUpdateOne {
	_u.mutation.AddAppliedPolicy(v)
	return _u
}

// SetAppliedConfig sets the "applied_config" field.
func (_u *CoreUpdateOne) SetAppliedConfig(v []byte) *CoreUpdateOne {
	_u.mutation.SetAppliedConfig(v)
	return _u
}

// ClearAppliedConfig clears the value of the "applied_config" field.
func (_u *CoreUpdateOne) ClearAppliedConfig() *CoreUpdateOne {
	_u.mutation.ClearAppliedConfig()
	return _u
}

// SetStage sets the "stage" field.
func (_u *CoreUpdateOne) SetStage(v string) *CoreUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillableStage(v *string) *CoreUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetPendingTask sets the "pending_task" field.
func (_u *CoreUpdateOne) SetPendingTask(v string) *CoreUpdateOne {
	_u.mutation.SetPendingTask(v)
	return _u
}

// SetNillablePendingTask sets the "pending_task" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillablePendingTask(v *string) *CoreUpdateOne {
	if v != nil {
		_u.SetPendingTask(*v)
	}
	return _u
}

// SetPendingRevision sets the "pending_revision" field.
func (_u *CoreUpdateOne) SetPendingRevision(v string) *CoreUpdateOne {
	_u.mutation.SetPendingRevision(v)
	return _u
}

// SetNillablePendingRevision sets the "pending_revision" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillablePendingRevision(v *string) *CoreUpdateOne {
	if v != nil {
		_u.SetPendingRevision(*v)
	}
	return _u
}

// SetPendingPolicy sets the "pending_policy" field.
func (_u *CoreUpdateOne) SetPendingPolicy(v int64) *CoreUpdateOne {
	_u.mutation.ResetPendingPolicy()
	_u.mutation.SetPendingPolicy(v)
	return _u
}

// SetNillablePendingPolicy sets the "pending_policy" field if the given value is not nil.
func (_u *CoreUpdateOne) SetNillablePendingPolicy(v *int64) *CoreUpdateOne {
	if v != nil {
		_u.SetPendingPolicy(*v)
	}
	return _u
}

// AddPendingPolicy adds value to the "pending_policy" field.
func (_u *CoreUpdateOne) AddPendingPolicy(v int64) *CoreUpdateOne {
	_u.mutation.AddPendingPolicy(v)
	return _u
}

// SetPendingConfig sets the "pending_config" field.
func (_u *CoreUpdateOne) SetPendingConfig(v []byte) *CoreUpdateOne {
	_u.mutation.SetPendingConfig(v)
	return _u
}

// ClearPendingConfig clears the value of the "pending_config" field.
func (_u *CoreUpdateOne) ClearPendingConfig() *CoreUpdateOne {
	_u.mutation.ClearPendingConfig()
	return _u
}

// Mutation returns the CoreMutation object of the builder.
func (_u *CoreUpdateOne) Mutation() *CoreMutation {
	return _u.mutation
}

// Where appends a list predicates to the CoreUpdate builder.
func (_u *CoreUpdateOne) Where(ps ...predicate.Core) *CoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoreUpdateOne) Select(field string, fields ...string) *CoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Core entity.
func (_u *CoreUpdateOne) Save(ctx context.Context) (*Core, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreUpdateOne) SaveX(ctx context.Context) *Core {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoreUpdateOne) check() error {
	if v, ok := _u.mutation.PolicyFloor(); ok {
		if err := core.PolicyFloorValidator(v); err != nil {
			return &ValidationError{Name: "policy_floor", err: fmt.Errorf(`ent: validator failed for field "Core.policy_floor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppliedPolicy(); ok {
		if err := core.AppliedPolicyValidator(v); err != nil {
			return &ValidationError{Name: "applied_policy", err: fmt.Errorf(`ent: validator failed for field "Core.applied_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingPolicy(); ok {
		if err := core.PendingPolicyValidator(v); err != nil {
			return &ValidationError{Name: "pending_policy", err: fmt.Errorf(`ent: validator failed for field "Core.pending_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *CoreUpdateOne) sqlSave(ctx context.Context) (_node *Core, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(core.Table, core.Columns, sqlgraph.NewFieldSpec(core.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Core.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, core.FieldID)
		for _, f := range fields {
			if !core.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != core.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyFloor(); ok {
		_spec.SetField(core.FieldPolicyFloor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPolicyFloor(); ok {
		_spec.AddField(core.FieldPolicyFloor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Authorization(); ok {
		_spec.SetField(core.FieldAuthorization, field.TypeBytes, value)
	}
	if _u.mutation.AuthorizationCleared() {
		_spec.ClearField(core.FieldAuthorization, field.TypeBytes)
	}
	if value, ok := _u.mutation.AppliedRevision(); ok {
		_spec.SetField(core.FieldAppliedRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppliedPolicy(); ok {
		_spec.SetField(core.FieldAppliedPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedPolicy(); ok {
		_spec.AddField(core.FieldAppliedPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AppliedConfig(); ok {
		_spec.SetField(core.FieldAppliedConfig, field.TypeBytes, value)
	}
	if _u.mutation.AppliedConfigCleared() {
		_spec.ClearField(core.FieldAppliedConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(core.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingTask(); ok {
		_spec.SetField(core.FieldPendingTask, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingRevision(); ok {
		_spec.SetField(core.FieldPendingRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingPolicy(); ok {
		_spec.SetField(core.FieldPendingPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingPolicy(); ok {
		_spec.AddField(core.FieldPendingPolicy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingConfig(); ok {
		_spec.SetField(core.FieldPendingConfig, field.TypeBytes, value)
	}
	if _u.mutation.PendingConfigCleared() {
		_spec.ClearField(core.FieldPendingConfig, field.TypeBytes)
	}
	_node = &Core{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{core.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
