// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/core"
)

// Core is the model entity for the Core schema.
type Core struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// PolicyFloor holds the value of the "policy_floor" field.
	PolicyFloor int64 `json:"policy_floor,omitempty"`
	// Authorization holds the value of the "authorization" field.
	Authorization []byte `json:"authorization,omitempty"`
	// AppliedRevision holds the value of the "applied_revision" field.
	AppliedRevision string `json:"applied_revision,omitempty"`
	// AppliedPolicy holds the value of the "applied_policy" field.
	AppliedPolicy int64 `json:"applied_policy,omitempty"`
	// AppliedConfig holds the value of the "applied_config" field.
	AppliedConfig []byte `json:"applied_config,omitempty"`
	// Stage holds the value of the "stage" field.
	Stage string `json:"stage,omitempty"`
	// PendingTask holds the value of the "pending_task" field.
	PendingTask string `json:"pending_task,omitempty"`
	// PendingRevision holds the value of the "pending_revision" field.
	PendingRevision string `json:"pending_revision,omitempty"`
	// PendingPolicy holds the value of the "pending_policy" field.
	PendingPolicy int64 `json:"pending_policy,omitempty"`
	// PendingConfig holds the value of the "pending_config" field.
	PendingConfig []byte `json:"pending_config,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Core) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case core.FieldAuthorization, core.FieldAppliedConfig, core.FieldPendingConfig:
			values[i] = new([]byte)
		case core.FieldPolicyFloor, core.FieldAppliedPolicy, core.FieldPendingPolicy:
			values[i] = new(sql.NullInt64)
		case core.FieldID, core.FieldAppliedRevision, core.FieldStage, core.FieldPendingTask, core.FieldPendingRevision:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Core fields.
func (_m *Core) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case core.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case core.FieldPolicyFloor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_floor", values[i])
			} else if value.Valid {
				_m.PolicyFloor = value.Int64
			}
		case core.FieldAuthorization:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field authorization", values[i])
			} else if value != nil {
				_m.Authorization = *value
			}
		case core.FieldAppliedRevision:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field applied_revision", values[i])
			} else if value.Valid {
				_m.AppliedRevision = value.String
			}
		case core.FieldAppliedPolicy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_policy", values[i])
			} else if value.Valid {
				_m.AppliedPolicy = value.Int64
			}
		case core.FieldAppliedConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field applied_config", values[i])
			} else if value != nil {
				_m.AppliedConfig = *value
			}
		case core.FieldStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stage", values[i])
			} else if value.Valid {
				_m.Stage = value.String
			}
		case core.FieldPendingTask:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pending_task", values[i])
			} else if value.Valid {
				_m.PendingTask = value.String
			}
		case core.FieldPendingRevision:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pending_revision", values[i])
			} else if value.Valid {
				_m.PendingRevision = value.String
			}
		case core.FieldPendingPolicy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_policy", values[i])
			} else if value.Valid {
				_m.PendingPolicy = value.Int64
			}
		case core.FieldPendingConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pending_config", values[i])
			} else if value != nil {
				_m.PendingConfig = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Core.
// This includes values selected through modifiers, order, etc.
func (_m *Core) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Core.
// Note that you need to call Core.Unwrap() before calling this method if this Core
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Core) Update() *CoreUpdateOne {
	return NewCoreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Core entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Core) Unwrap() *Core {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Core is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Core) String() string {
	var builder strings.Builder
	builder.WriteString("Core(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("policy_floor=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyFloor))
	builder.WriteString(", ")
	builder.WriteString("authorization=")
	builder.WriteString(fmt.Sprintf("%v", _m.Authorization))
	builder.WriteString(", ")
	builder.WriteString("applied_revision=")
	builder.WriteString(_m.AppliedRevision)
	builder.WriteString(", ")
	builder.WriteString("applied_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedPolicy))
	builder.WriteString(", ")
	builder.WriteString("applied_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedConfig))
	builder.WriteString(", ")
	builder.WriteString("stage=")
	builder.WriteString(_m.Stage)
	builder.WriteString(", ")
	builder.WriteString("pending_task=")
	builder.WriteString(_m.PendingTask)
	builder.WriteString(", ")
	builder.WriteString("pending_revision=")
	builder.WriteString(_m.PendingRevision)
	builder.WriteString(", ")
	builder.WriteString("pending_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingPolicy))
	builder.WriteString(", ")
	builder.WriteString("pending_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingConfig))
	builder.WriteByte(')')
	return builder.String()
}

// Cores is a parsable slice of Core.
type Cores []*Core
