// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/core"
)

// CoreCreate is the builder for creating a Core entity.
type CoreCreate struct {
	config
	mutation *CoreMutation
	hooks    []Hook
}

// SetPolicyFloor sets the "policy_floor" field.
func (_c *CoreCreate) SetPolicyFloor(v int64) *CoreCreate {
	_c.mutation.SetPolicyFloor(v)
	return _c
}

// SetNillablePolicyFloor sets the "policy_floor" field if the given value is not nil.
func (_c *CoreCreate) SetNillablePolicyFloor(v *int64) *CoreCreate {
	if v != nil {
		_c.SetPolicyFloor(*v)
	}
	return _c
}

// SetAuthorization sets the "authorization" field.
func (_c *CoreCreate) SetAuthorization(v []byte) *CoreCreate {
	_c.mutation.SetAuthorization(v)
	return _c
}

// SetAppliedRevision sets the "applied_revision" field.
func (_c *CoreCreate) SetAppliedRevision(v string) *CoreCreate {
	_c.mutation.SetAppliedRevision(v)
	return _c
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_c *CoreCreate) SetNillableAppliedRevision(v *string) *CoreCreate {
	if v != nil {
		_c.SetAppliedRevision(*v)
	}
	return _c
}

// SetAppliedPolicy sets the "applied_policy" field.
func (_c *CoreCreate) SetAppliedPolicy(v int64) *CoreCreate {
	_c.mutation.SetAppliedPolicy(v)
	return _c
}

// SetNillableAppliedPolicy sets the "applied_policy" field if the given value is not nil.
func (_c *CoreCreate) SetNillableAppliedPolicy(v *int64) *CoreCreate {
	if v != nil {
		_c.SetAppliedPolicy(*v)
	}
	return _c
}

// SetAppliedConfig sets the "applied_config" field.
func (_c *CoreCreate) SetAppliedConfig(v []byte) *CoreCreate {
	_c.mutation.SetAppliedConfig(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *CoreCreate) SetStage(v string) *CoreCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *CoreCreate) SetNillableStage(v *string) *CoreCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetPendingTask sets the "pending_task" field.
func (_c *CoreCreate) SetPendingTask(v string) *CoreCreate {
	_c.mutation.SetPendingTask(v)
	return _c
}

// SetNillablePendingTask sets the "pending_task" field if the given value is not nil.
func (_c *CoreCreate) SetNillablePendingTask(v *string) *CoreCreate {
	if v != nil {
		_c.SetPendingTask(*v)
	}
	return _c
}

// SetPendingRevision sets the "pending_revision" field.
func (_c *CoreCreate) SetPendingRevision(v string) *CoreCreate {
	_c.mutation.SetPendingRevision(v)
	return _c
}

// SetNillablePendingRevision sets the "pending_revision" field if the given value is not nil.
func (_c *CoreCreate) SetNillablePendingRevision(v *string) *CoreCreate {
	if v != nil {
		_c.SetPendingRevision(*v)
	}
	return _c
}

// SetPendingPolicy sets the "pending_policy" field.
func (_c *CoreCreate) SetPendingPolicy(v int64) *CoreCreate {
	_c.mutation.SetPendingPolicy(v)
	return _c
}

// SetNillablePendingPolicy sets the "pending_policy" field if the given value is not nil.
func (_c *CoreCreate) SetNillablePendingPolicy(v *int64) *CoreCreate {
	if v != nil {
		_c.SetPendingPolicy(*v)
	}
	return _c
}

// SetPendingConfig sets the "pending_config" field.
func (_c *CoreCreate) SetPendingConfig(v []byte) *CoreCreate {
	_c.mutation.SetPendingConfig(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CoreCreate) SetID(v string) *CoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CoreMutation object of the builder.
func (_c *CoreCreate) Mutation() *CoreMutation {
	return _c.mutation
}

// Save creates the Core in the database.
func (_c *CoreCreate) Save(ctx context.Context) (*Core, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CoreCreate) SaveX(ctx context.Context) *Core {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CoreCreate) defaults() {
	if _, ok := _c.mutation.PolicyFloor(); !ok {
		v := core.DefaultPolicyFloor
		_c.mutation.SetPolicyFloor(v)
	}
	if _, ok := _c.mutation.AppliedRevision(); !ok {
		v := core.DefaultAppliedRevision
		_c.mutation.SetAppliedRevision(v)
	}
	if _, ok := _c.mutation.AppliedPolicy(); !ok {
		v := core.DefaultAppliedPolicy
		_c.mutation.SetAppliedPolicy(v)
	}
	if _, ok := _c.mutation.Stage(); !ok {
		v := core.DefaultStage
		_c.mutation.SetStage(v)
	}
	if _, ok := _c.mutation.PendingTask(); !ok {
		v := core.DefaultPendingTask
		_c.mutation.SetPendingTask(v)
	}
	if _, ok := _c.mutation.PendingRevision(); !ok {
		v := core.DefaultPendingRevision
		_c.mutation.SetPendingRevision(v)
	}
	if _, ok := _c.mutation.PendingPolicy(); !ok {
		v := core.DefaultPendingPolicy
		_c.mutation.SetPendingPolicy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CoreCreate) check() error {
	if _, ok := _c.mutation.PolicyFloor(); !ok {
		return &ValidationError{Name: "policy_floor", err: errors.New(`ent: missing required field "Core.policy_floor"`)}
	}
	if v, ok := _c.mutation.PolicyFloor(); ok {
		if err := core.PolicyFloorValidator(v); err != nil {
			return &ValidationError{Name: "policy_floor", err: fmt.Errorf(`ent: validator failed for field "Core.policy_floor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedRevision(); !ok {
		return &ValidationError{Name: "applied_revision", err: errors.New(`ent: missing required field "Core.applied_revision"`)}
	}
	if _, ok := _c.mutation.AppliedPolicy(); !ok {
		return &ValidationError{Name: "applied_policy", err: errors.New(`ent: missing required field "Core.applied_policy"`)}
	}
	if v, ok := _c.mutation.AppliedPolicy(); ok {
		if err := core.AppliedPolicyValidator(v); err != nil {
			return &ValidationError{Name: "applied_policy", err: fmt.Errorf(`ent: validator failed for field "Core.applied_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "Core.stage"`)}
	}
	if _, ok := _c.mutation.PendingTask(); !ok {
		return &ValidationError{Name: "pending_task", err: errors.New(`ent: missing required field "Core.pending_task"`)}
	}
	if _, ok := _c.mutation.PendingRevision(); !ok {
		return &ValidationError{Name: "pending_revision", err: errors.New(`ent: missing required field "Core.pending_revision"`)}
	}
	if _, ok := _c.mutation.PendingPolicy(); !ok {
		return &ValidationError{Name: "pending_policy", err: errors.New(`ent: missing required field "Core.pending_policy"`)}
	}
	if v, ok := _c.mutation.PendingPolicy(); ok {
		if err := core.PendingPolicyValidator(v); err != nil {
			return &ValidationError{Name: "pending_policy", err: fmt.Errorf(`ent: validator failed for field "Core.pending_policy": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := core.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Core.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CoreCreate) sqlSave(ctx context.Context) (*Core, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Core.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CoreCreate) createSpec() (*Core, *sqlgraph.CreateSpec) {
	var (
		_node = &Core{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(core.Table, sqlgraph.NewFieldSpec(core.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PolicyFloor(); ok {
		_spec.SetField(core.FieldPolicyFloor, field.TypeInt64, value)
		_node.PolicyFloor = value
	}
	if value, ok := _c.mutation.Authorization(); ok {
		_spec.SetField(core.FieldAuthorization, field.TypeBytes, value)
		_node.Authorization = value
	}
	if value, ok := _c.mutation.AppliedRevision(); ok {
		_spec.SetField(core.FieldAppliedRevision, field.TypeString, value)
		_node.AppliedRevision = value
	}
	if value, ok := _c.mutation.AppliedPolicy(); ok {
		_spec.SetField(core.FieldAppliedPolicy, field.TypeInt64, value)
		_node.AppliedPolicy = value
	}
	if value, ok := _c.mutation.AppliedConfig(); ok {
		_spec.SetField(core.FieldAppliedConfig, field.TypeBytes, value)
		_node.AppliedConfig = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(core.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.PendingTask(); ok {
		_spec.SetField(core.FieldPendingTask, field.TypeString, value)
		_node.PendingTask = value
	}
	if value, ok := _c.mutation.PendingRevision(); ok {
		_spec.SetField(core.FieldPendingRevision, field.TypeString, value)
		_node.PendingRevision = value
	}
	if value, ok := _c.mutation.PendingPolicy(); ok {
		_spec.SetField(core.FieldPendingPolicy, field.TypeInt64, value)
		_node.PendingPolicy = value
	}
	if value, ok := _c.mutation.PendingConfig(); ok {
		_spec.SetField(core.FieldPendingConfig, field.TypeBytes, value)
		_node.PendingConfig = value
	}
	return _node, _spec
}

// CoreCreateBulk is the builder for creating many Core entities in bulk.
type CoreCreateBulk struct {
	config
	err      error
	builders []*CoreCreate
}

// Save creates the Core entities in the database.
func (_c *CoreCreateBulk) Save(ctx context.Context) ([]*Core, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Core, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CoreCreateBulk) SaveX(ctx context.Context) []*Core {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
