// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/cursor"
)

// CursorCreate is the builder for creating a Cursor entity.
type CursorCreate struct {
	config
	mutation *CursorMutation
	hooks    []Hook
}

// SetRuntimeID sets the "runtime_id" field.
func (_c *CursorCreate) SetRuntimeID(v string) *CursorCreate {
	_c.mutation.SetRuntimeID(v)
	return _c
}

// SetUpload sets the "upload" field.
func (_c *CursorCreate) SetUpload(v int64) *CursorCreate {
	_c.mutation.SetUpload(v)
	return _c
}

// SetDownload sets the "download" field.
func (_c *CursorCreate) SetDownload(v int64) *CursorCreate {
	_c.mutation.SetDownload(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *CursorCreate) SetObservedAt(v int64) *CursorCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetClosed sets the "closed" field.
func (_c *CursorCreate) SetClosed(v bool) *CursorCreate {
	_c.mutation.SetClosed(v)
	return _c
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_c *CursorCreate) SetNillableClosed(v *bool) *CursorCreate {
	if v != nil {
		_c.SetClosed(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CursorCreate) SetID(v string) *CursorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CursorMutation object of the builder.
func (_c *CursorCreate) Mutation() *CursorMutation {
	return _c.mutation
}

// Save creates the Cursor in the database.
func (_c *CursorCreate) Save(ctx context.Context) (*Cursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CursorCreate) SaveX(ctx context.Context) *Cursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CursorCreate) defaults() {
	if _, ok := _c.mutation.Closed(); !ok {
		v := cursor.DefaultClosed
		_c.mutation.SetClosed(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CursorCreate) check() error {
	if _, ok := _c.mutation.RuntimeID(); !ok {
		return &ValidationError{Name: "runtime_id", err: errors.New(`ent: missing required field "Cursor.runtime_id"`)}
	}
	if v, ok := _c.mutation.RuntimeID(); ok {
		if err := cursor.RuntimeIDValidator(v); err != nil {
			return &ValidationError{Name: "runtime_id", err: fmt.Errorf(`ent: validator failed for field "Cursor.runtime_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Upload(); !ok {
		return &ValidationError{Name: "upload", err: errors.New(`ent: missing required field "Cursor.upload"`)}
	}
	if v, ok := _c.mutation.Upload(); ok {
		if err := cursor.UploadValidator(v); err != nil {
			return &ValidationError{Name: "upload", err: fmt.Errorf(`ent: validator failed for field "Cursor.upload": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Download(); !ok {
		return &ValidationError{Name: "download", err: errors.New(`ent: missing required field "Cursor.download"`)}
	}
	if v, ok := _c.mutation.Download(); ok {
		if err := cursor.DownloadValidator(v); err != nil {
			return &ValidationError{Name: "download", err: fmt.Errorf(`ent: validator failed for field "Cursor.download": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "Cursor.observed_at"`)}
	}
	if _, ok := _c.mutation.Closed(); !ok {
		return &ValidationError{Name: "closed", err: errors.New(`ent: missing required field "Cursor.closed"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := cursor.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Cursor.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CursorCreate) sqlSave(ctx context.Context) (*Cursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Cursor.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CursorCreate) createSpec() (*Cursor, *sqlgraph.CreateSpec) {
	var (
		_node = &Cursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cursor.Table, sqlgraph.NewFieldSpec(cursor.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RuntimeID(); ok {
		_spec.SetField(cursor.FieldRuntimeID, field.TypeString, value)
		_node.RuntimeID = value
	}
	if value, ok := _c.mutation.Upload(); ok {
		_spec.SetField(cursor.FieldUpload, field.TypeInt64, value)
		_node.Upload = value
	}
	if value, ok := _c.mutation.Download(); ok {
		_spec.SetField(cursor.FieldDownload, field.TypeInt64, value)
		_node.Download = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(cursor.FieldObservedAt, field.TypeInt64, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.Closed(); ok {
		_spec.SetField(cursor.FieldClosed, field.TypeBool, value)
		_node.Closed = value
	}
	return _node, _spec
}

// CursorCreateBulk is the builder for creating many Cursor entities in bulk.
type CursorCreateBulk struct {
	config
	err      error
	builders []*CursorCreate
}

// Save creates the Cursor entities in the database.
func (_c *CursorCreateBulk) Save(ctx context.Context) ([]*Cursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Cursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CursorCreateBulk) SaveX(ctx context.Context) []*Cursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
