// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/cursor"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
)

// CursorUpdate is the builder for updating Cursor entities.
type CursorUpdate struct {
	config
	hooks    []Hook
	mutation *CursorMutation
}

// Where appends a list predicates to the CursorUpdate builder.
func (_u *CursorUpdate) Where(ps ...predicate.Cursor) *CursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRuntimeID sets the "runtime_id" field.
func (_u *CursorUpdate) SetRuntimeID(v string) *CursorUpdate {
	_u.mutation.SetRuntimeID(v)
	return _u
}

// SetNillableRuntimeID sets the "runtime_id" field if the given value is not nil.
func (_u *CursorUpdate) SetNillableRuntimeID(v *string) *CursorUpdate {
	if v != nil {
		_u.SetRuntimeID(*v)
	}
	return _u
}

// SetUpload sets the "upload" field.
func (_u *CursorUpdate) SetUpload(v int64) *CursorUpdate {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *CursorUpdate) SetNillableUpload(v *int64) *CursorUpdate {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *CursorUpdate) AddUpload(v int64) *CursorUpdate {
	_u.mutation.AddUpload(v)
	return _u
}

// SetDownload sets the "download" field.
func (_u *CursorUpdate) SetDownload(v int64) *CursorUpdate {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *CursorUpdate) SetNillableDownload(v *int64) *CursorUpdate {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *CursorUpdate) AddDownload(v int64) *CursorUpdate {
	_u.mutation.AddDownload(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *CursorUpdate) SetObservedAt(v int64) *CursorUpdate {
	_u.mutation.ResetObservedAt()
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *CursorUpdate) SetNillableObservedAt(v *int64) *CursorUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// AddObservedAt adds value to the "observed_at" field.
func (_u *CursorUpdate) AddObservedAt(v int64) *CursorUpdate {
	_u.mutation.AddObservedAt(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *CursorUpdate) SetClosed(v bool) *CursorUpdate {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *CursorUpdate) SetNillableClosed(v *bool) *CursorUpdate {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// Mutation returns the CursorMutation object of the builder.
func (_u *CursorUpdate) Mutation() *CursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CursorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CursorUpdate) check() error {
	if v, ok := _u.mutation.RuntimeID(); ok {
		if err := cursor.RuntimeIDValidator(v); err != nil {
			return &ValidationError{Name: "runtime_id", err: fmt.Errorf(`ent: validator failed for field "Cursor.runtime_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Upload(); ok {
		if err := cursor.UploadValidator(v); err != nil {
			return &ValidationError{Name: "upload", err: fmt.Errorf(`ent: validator failed for field "Cursor.upload": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Download(); ok {
		if err := cursor.DownloadValidator(v); err != nil {
			return &ValidationError{Name: "download", err: fmt.Errorf(`ent: validator failed for field "Cursor.download": %w`, err)}
		}
	}
	return nil
}

func (_u *CursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cursor.Table, cursor.Columns, sqlgraph.NewFieldSpec(cursor.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuntimeID(); ok {
		_spec.SetField(cursor.FieldRuntimeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(cursor.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(cursor.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(cursor.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(cursor.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(cursor.FieldObservedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObservedAt(); ok {
		_spec.AddField(cursor.FieldObservedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(cursor.FieldClosed, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CursorUpdateOne is the builder for updating a single Cursor entity.
type CursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CursorMutation
}

// SetRuntimeID sets the "runtime_id" field.
func (_u *CursorUpdateOne) SetRuntimeID(v string) *CursorUpdateOne {
	_u.mutation.SetRuntimeID(v)
	return _u
}

// SetNillableRuntimeID sets the "runtime_id" field if the given value is not nil.
func (_u *CursorUpdateOne) SetNillableRuntimeID(v *string) *CursorUpdateOne {
	if v != nil {
		_u.SetRuntimeID(*v)
	}
	return _u
}

// SetUpload sets the "upload" field.
func (_u *CursorUpdateOne) SetUpload(v int64) *CursorUpdateOne {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *CursorUpdateOne) SetNillableUpload(v *int64) *CursorUpdateOne {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *CursorUpdateOne) AddUpload(v int64) *CursorUpdateOne {
	_u.mutation.AddUpload(v)
	return _u
}

// SetDownload sets the "download" field.
func (_u *CursorUpdateOne) SetDownload(v int64) *CursorUpdateOne {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *CursorUpdateOne) SetNillableDownload(v *int64) *CursorUpdateOne {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *CursorUpdateOne) AddDownload(v int64) *CursorUpdateOne {
	_u.mutation.AddDownload(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *CursorUpdateOne) SetObservedAt(v int64) *CursorUpdateOne {
	_u.mutation.ResetObservedAt()
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *CursorUpdateOne) SetNillableObservedAt(v *int64) *CursorUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// AddObservedAt adds value to the "observed_at" field.
func (_u *CursorUpdateOne) AddObservedAt(v int64) *CursorUpdateOne {
	_u.mutation.AddObservedAt(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *CursorUpdateOne) SetClosed(v bool) *CursorUpdateOne {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *CursorUpdateOne) SetNillableClosed(v *bool) *CursorUpdateOne {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// Mutation returns the CursorMutation object of the builder.
func (_u *CursorUpdateOne) Mutation() *CursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the CursorUpdate builder.
func (_u *CursorUpdateOne) Where(ps ...predicate.Cursor) *CursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CursorUpdateOne) Select(field string, fields ...string) *CursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Cursor entity.
func (_u *CursorUpdateOne) Save(ctx context.Context) (*Cursor, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CursorUpdateOne) SaveX(ctx context.Context) *Cursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CursorUpdateOne) check() error {
	if v, ok := _u.mutation.RuntimeID(); ok {
		if err := cursor.RuntimeIDValidator(v); err != nil {
			return &ValidationError{Name: "runtime_id", err: fmt.Errorf(`ent: validator failed for field "Cursor.runtime_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Upload(); ok {
		if err := cursor.UploadValidator(v); err != nil {
			return &ValidationError{Name: "upload", err: fmt.Errorf(`ent: validator failed for field "Cursor.upload": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Download(); ok {
		if err := cursor.DownloadValidator(v); err != nil {
			return &ValidationError{Name: "download", err: fmt.Errorf(`ent: validator failed for field "Cursor.download": %w`, err)}
		}
	}
	return nil
}

func (_u *CursorUpdateOne) sqlSave(ctx context.Context) (_node *Cursor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cursor.Table, cursor.Columns, sqlgraph.NewFieldSpec(cursor.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cursor.FieldID)
		for _, f := range fields {
			if !cursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuntimeID(); ok {
		_spec.SetField(cursor.FieldRuntimeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(cursor.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(cursor.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(cursor.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(cursor.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(cursor.FieldObservedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObservedAt(); ok {
		_spec.AddField(cursor.FieldObservedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(cursor.FieldClosed, field.TypeBool, value)
	}
	_node = &Cursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
