// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/cursor"
)

// Cursor is the model entity for the Cursor schema.
type Cursor struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RuntimeID holds the value of the "runtime_id" field.
	RuntimeID string `json:"runtime_id,omitempty"`
	// Upload holds the value of the "upload" field.
	Upload int64 `json:"upload,omitempty"`
	// Download holds the value of the "download" field.
	Download int64 `json:"download,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt int64 `json:"observed_at,omitempty"`
	// Closed holds the value of the "closed" field.
	Closed       bool `json:"closed,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cursor.FieldClosed:
			values[i] = new(sql.NullBool)
		case cursor.FieldUpload, cursor.FieldDownload, cursor.FieldObservedAt:
			values[i] = new(sql.NullInt64)
		case cursor.FieldID, cursor.FieldRuntimeID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cursor fields.
func (_m *Cursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cursor.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case cursor.FieldRuntimeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runtime_id", values[i])
			} else if value.Valid {
				_m.RuntimeID = value.String
			}
		case cursor.FieldUpload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upload", values[i])
			} else if value.Valid {
				_m.Upload = value.Int64
			}
		case cursor.FieldDownload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download", values[i])
			} else if value.Valid {
				_m.Download = value.Int64
			}
		case cursor.FieldObservedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Int64
			}
		case cursor.FieldClosed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field closed", values[i])
			} else if value.Valid {
				_m.Closed = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cursor.
// This includes values selected through modifiers, order, etc.
func (_m *Cursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Cursor.
// Note that you need to call Cursor.Unwrap() before calling this method if this Cursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Cursor) Update() *CursorUpdateOne {
	return NewCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Cursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Cursor) Unwrap() *Cursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Cursor) String() string {
	var builder strings.Builder
	builder.WriteString("Cursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("runtime_id=")
	builder.WriteString(_m.RuntimeID)
	builder.WriteString(", ")
	builder.WriteString("upload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Upload))
	builder.WriteString(", ")
	builder.WriteString("download=")
	builder.WriteString(fmt.Sprintf("%v", _m.Download))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.ObservedAt))
	builder.WriteString(", ")
	builder.WriteString("closed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Closed))
	builder.WriteByte(')')
	return builder.String()
}

// Cursors is a parsable slice of Cursor.
type Cursors []*Cursor
