// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/batch"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/core"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/cursor"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/schema"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/stream"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	batchFields := schema.Batch{}.Fields()
	_ = batchFields
	// batchDescSeq is the schema descriptor for seq field.
	batchDescSeq := batchFields[1].Descriptor()
	// batch.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	batch.SeqValidator = batchDescSeq.Validators[0].(func(int64) error)
	// batchDescStreamID is the schema descriptor for stream_id field.
	batchDescStreamID := batchFields[2].Descriptor()
	// batch.StreamIDValidator is a validator for the "stream_id" field. It is called by the builders before save.
	batch.StreamIDValidator = batchDescStreamID.Validators[0].(func(string) error)
	// batchDescSizeBytes is the schema descriptor for size_bytes field.
	batchDescSizeBytes := batchFields[3].Descriptor()
	// batch.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	batch.DefaultSizeBytes = batchDescSizeBytes.Default.(int64)
	// batch.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	batch.SizeBytesValidator = batchDescSizeBytes.Validators[0].(func(int64) error)
	// batchDescPayloadHash is the schema descriptor for payload_hash field.
	batchDescPayloadHash := batchFields[5].Descriptor()
	// batch.PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	batch.PayloadHashValidator = batchDescPayloadHash.Validators[0].(func(string) error)
	// batchDescID is the schema descriptor for id field.
	batchDescID := batchFields[0].Descriptor()
	// batch.IDValidator is a validator for the "id" field. It is called by the builders before save.
	batch.IDValidator = batchDescID.Validators[0].(func(string) error)
	coreFields := schema.Core{}.Fields()
	_ = coreFields
	// coreDescPolicyFloor is the schema descriptor for policy_floor field.
	coreDescPolicyFloor := coreFields[1].Descriptor()
	// core.DefaultPolicyFloor holds the default value on creation for the policy_floor field.
	core.DefaultPolicyFloor = coreDescPolicyFloor.Default.(int64)
	// core.PolicyFloorValidator is a validator for the "policy_floor" field. It is called by the builders before save.
	core.PolicyFloorValidator = coreDescPolicyFloor.Validators[0].(func(int64) error)
	// coreDescAppliedRevision is the schema descriptor for applied_revision field.
	coreDescAppliedRevision := coreFields[3].Descriptor()
	// core.DefaultAppliedRevision holds the default value on creation for the applied_revision field.
	core.DefaultAppliedRevision = coreDescAppliedRevision.Default.(string)
	// coreDescAppliedPolicy is the schema descriptor for applied_policy field.
	coreDescAppliedPolicy := coreFields[4].Descriptor()
	// core.DefaultAppliedPolicy holds the default value on creation for the applied_policy field.
	core.DefaultAppliedPolicy = coreDescAppliedPolicy.Default.(int64)
	// core.AppliedPolicyValidator is a validator for the "applied_policy" field. It is called by the builders before save.
	core.AppliedPolicyValidator = coreDescAppliedPolicy.Validators[0].(func(int64) error)
	// coreDescStage is the schema descriptor for stage field.
	coreDescStage := coreFields[6].Descriptor()
	// core.DefaultStage holds the default value on creation for the stage field.
	core.DefaultStage = coreDescStage.Default.(string)
	// coreDescPendingTask is the schema descriptor for pending_task field.
	coreDescPendingTask := coreFields[7].Descriptor()
	// core.DefaultPendingTask holds the default value on creation for the pending_task field.
	core.DefaultPendingTask = coreDescPendingTask.Default.(string)
	// coreDescPendingRevision is the schema descriptor for pending_revision field.
	coreDescPendingRevision := coreFields[8].Descriptor()
	// core.DefaultPendingRevision holds the default value on creation for the pending_revision field.
	core.DefaultPendingRevision = coreDescPendingRevision.Default.(string)
	// coreDescPendingPolicy is the schema descriptor for pending_policy field.
	coreDescPendingPolicy := coreFields[9].Descriptor()
	// core.DefaultPendingPolicy holds the default value on creation for the pending_policy field.
	core.DefaultPendingPolicy = coreDescPendingPolicy.Default.(int64)
	// core.PendingPolicyValidator is a validator for the "pending_policy" field. It is called by the builders before save.
	core.PendingPolicyValidator = coreDescPendingPolicy.Validators[0].(func(int64) error)
	// coreDescID is the schema descriptor for id field.
	coreDescID := coreFields[0].Descriptor()
	// core.IDValidator is a validator for the "id" field. It is called by the builders before save.
	core.IDValidator = coreDescID.Validators[0].(func(string) error)
	cursorFields := schema.Cursor{}.Fields()
	_ = cursorFields
	// cursorDescRuntimeID is the schema descriptor for runtime_id field.
	cursorDescRuntimeID := cursorFields[1].Descriptor()
	// cursor.RuntimeIDValidator is a validator for the "runtime_id" field. It is called by the builders before save.
	cursor.RuntimeIDValidator = cursorDescRuntimeID.Validators[0].(func(string) error)
	// cursorDescUpload is the schema descriptor for upload field.
	cursorDescUpload := cursorFields[2].Descriptor()
	// cursor.UploadValidator is a validator for the "upload" field. It is called by the builders before save.
	cursor.UploadValidator = cursorDescUpload.Validators[0].(func(int64) error)
	// cursorDescDownload is the schema descriptor for download field.
	cursorDescDownload := cursorFields[3].Descriptor()
	// cursor.DownloadValidator is a validator for the "download" field. It is called by the builders before save.
	cursor.DownloadValidator = cursorDescDownload.Validators[0].(func(int64) error)
	// cursorDescClosed is the schema descriptor for closed field.
	cursorDescClosed := cursorFields[5].Descriptor()
	// cursor.DefaultClosed holds the default value on creation for the closed field.
	cursor.DefaultClosed = cursorDescClosed.Default.(bool)
	// cursorDescID is the schema descriptor for id field.
	cursorDescID := cursorFields[0].Descriptor()
	// cursor.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cursor.IDValidator = cursorDescID.Validators[0].(func(string) error)
	streamFields := schema.Stream{}.Fields()
	_ = streamFields
	// streamDescNextSeq is the schema descriptor for next_seq field.
	streamDescNextSeq := streamFields[1].Descriptor()
	// stream.DefaultNextSeq holds the default value on creation for the next_seq field.
	stream.DefaultNextSeq = streamDescNextSeq.Default.(int64)
	// stream.NextSeqValidator is a validator for the "next_seq" field. It is called by the builders before save.
	stream.NextSeqValidator = streamDescNextSeq.Validators[0].(func(int64) error)
	// streamDescCommittedSeq is the schema descriptor for committed_seq field.
	streamDescCommittedSeq := streamFields[2].Descriptor()
	// stream.DefaultCommittedSeq holds the default value on creation for the committed_seq field.
	stream.DefaultCommittedSeq = streamDescCommittedSeq.Default.(int64)
	// stream.CommittedSeqValidator is a validator for the "committed_seq" field. It is called by the builders before save.
	stream.CommittedSeqValidator = streamDescCommittedSeq.Validators[0].(func(int64) error)
	// streamDescPendingBytes is the schema descriptor for pending_bytes field.
	streamDescPendingBytes := streamFields[3].Descriptor()
	// stream.DefaultPendingBytes holds the default value on creation for the pending_bytes field.
	stream.DefaultPendingBytes = streamDescPendingBytes.Default.(int64)
	// stream.PendingBytesValidator is a validator for the "pending_bytes" field. It is called by the builders before save.
	stream.PendingBytesValidator = streamDescPendingBytes.Validators[0].(func(int64) error)
	// streamDescRecoveryIssue is the schema descriptor for recovery_issue field.
	streamDescRecoveryIssue := streamFields[4].Descriptor()
	// stream.DefaultRecoveryIssue holds the default value on creation for the recovery_issue field.
	stream.DefaultRecoveryIssue = streamDescRecoveryIssue.Default.(string)
	// streamDescID is the schema descriptor for id field.
	streamDescID := streamFields[0].Descriptor()
	// stream.IDValidator is a validator for the "id" field. It is called by the builders before save.
	stream.IDValidator = streamDescID.Validators[0].(func(string) error)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPayloadHash is the schema descriptor for payload_hash field.
	taskDescPayloadHash := taskFields[1].Descriptor()
	// task.PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	task.PayloadHashValidator = taskDescPayloadHash.Validators[0].(func(string) error)
	// taskDescKind is the schema descriptor for kind field.
	taskDescKind := taskFields[2].Descriptor()
	// task.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	task.KindValidator = taskDescKind.Validators[0].(func(string) error)
	// taskDescBindingEpoch is the schema descriptor for binding_epoch field.
	taskDescBindingEpoch := taskFields[4].Descriptor()
	// task.BindingEpochValidator is a validator for the "binding_epoch" field. It is called by the builders before save.
	task.BindingEpochValidator = taskDescBindingEpoch.Validators[0].(func(int64) error)
	// taskDescProgressSeq is the schema descriptor for progress_seq field.
	taskDescProgressSeq := taskFields[6].Descriptor()
	// task.DefaultProgressSeq holds the default value on creation for the progress_seq field.
	task.DefaultProgressSeq = taskDescProgressSeq.Default.(int64)
	// task.ProgressSeqValidator is a validator for the "progress_seq" field. It is called by the builders before save.
	task.ProgressSeqValidator = taskDescProgressSeq.Validators[0].(func(int64) error)
	// taskDescAcknowledged is the schema descriptor for acknowledged field.
	taskDescAcknowledged := taskFields[8].Descriptor()
	// task.DefaultAcknowledged holds the default value on creation for the acknowledged field.
	task.DefaultAcknowledged = taskDescAcknowledged.Default.(bool)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.IDValidator is a validator for the "id" field. It is called by the builders before save.
	task.IDValidator = taskDescID.Validators[0].(func(string) error)
}
