// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/stream"
)

// StreamUpdate is the builder for updating Stream entities.
type StreamUpdate struct {
	config
	hooks    []Hook
	mutation *StreamMutation
}

// Where appends a list predicates to the StreamUpdate builder.
func (_u *StreamUpdate) Where(ps ...predicate.Stream) *StreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNextSeq sets the "next_seq" field.
func (_u *StreamUpdate) SetNextSeq(v int64) *StreamUpdate {
	_u.mutation.ResetNextSeq()
	_u.mutation.SetNextSeq(v)
	return _u
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableNextSeq(v *int64) *StreamUpdate {
	if v != nil {
		_u.SetNextSeq(*v)
	}
	return _u
}

// AddNextSeq adds value to the "next_seq" field.
func (_u *StreamUpdate) AddNextSeq(v int64) *StreamUpdate {
	_u.mutation.AddNextSeq(v)
	return _u
}

// SetCommittedSeq sets the "committed_seq" field.
func (_u *StreamUpdate) SetCommittedSeq(v int64) *StreamUpdate {
	_u.mutation.ResetCommittedSeq()
	_u.mutation.SetCommittedSeq(v)
	return _u
}

// SetNillableCommittedSeq sets the "committed_seq" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableCommittedSeq(v *int64) *StreamUpdate {
	if v != nil {
		_u.SetCommittedSeq(*v)
	}
	return _u
}

// AddCommittedSeq adds value to the "committed_seq" field.
func (_u *StreamUpdate) AddCommittedSeq(v int64) *StreamUpdate {
	_u.mutation.AddCommittedSeq(v)
	return _u
}

// SetPendingBytes sets the "pending_bytes" field.
func (_u *StreamUpdate) SetPendingBytes(v int64) *StreamUpdate {
	_u.mutation.ResetPendingBytes()
	_u.mutation.SetPendingBytes(v)
	return _u
}

// SetNillablePendingBytes sets the "pending_bytes" field if the given value is not nil.
func (_u *StreamUpdate) SetNillablePendingBytes(v *int64) *StreamUpdate {
	if v != nil {
		_u.SetPendingBytes(*v)
	}
	return _u
}

// AddPendingBytes adds value to the "pending_bytes" field.
func (_u *StreamUpdate) AddPendingBytes(v int64) *StreamUpdate {
	_u.mutation.AddPendingBytes(v)
	return _u
}

// SetRecoveryIssue sets the "recovery_issue" field.
func (_u *StreamUpdate) SetRecoveryIssue(v string) *StreamUpdate {
	_u.mutation.SetRecoveryIssue(v)
	return _u
}

// SetNillableRecoveryIssue sets the "recovery_issue" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableRecoveryIssue(v *string) *StreamUpdate {
	if v != nil {
		_u.SetRecoveryIssue(*v)
	}
	return _u
}

// Mutation returns the StreamMutation object of the builder.
func (_u *StreamUpdate) Mutation() *StreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StreamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StreamUpdate) check() error {
	if v, ok := _u.mutation.NextSeq(); ok {
		if err := stream.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.next_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommittedSeq(); ok {
		if err := stream.CommittedSeqValidator(v); err != nil {
			return &ValidationError{Name: "committed_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.committed_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingBytes(); ok {
		if err := stream.PendingBytesValidator(v); err != nil {
			return &ValidationError{Name: "pending_bytes", err: fmt.Errorf(`ent: validator failed for field "Stream.pending_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *StreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stream.Table, stream.Columns, sqlgraph.NewFieldSpec(stream.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NextSeq(); ok {
		_spec.SetField(stream.FieldNextSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextSeq(); ok {
		_spec.AddField(stream.FieldNextSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommittedSeq(); ok {
		_spec.SetField(stream.FieldCommittedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommittedSeq(); ok {
		_spec.AddField(stream.FieldCommittedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingBytes(); ok {
		_spec.SetField(stream.FieldPendingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingBytes(); ok {
		_spec.AddField(stream.FieldPendingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveryIssue(); ok {
		_spec.SetField(stream.FieldRecoveryIssue, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StreamUpdateOne is the builder for updating a single Stream entity.
type StreamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StreamMutation
}

// SetNextSeq sets the "next_seq" field.
func (_u *StreamUpdateOne) SetNextSeq(v int64) *StreamUpdateOne {
	_u.mutation.ResetNextSeq()
	_u.mutation.SetNextSeq(v)
	return _u
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableNextSeq(v *int64) *StreamUpdateOne {
	if v != nil {
		_u.SetNextSeq(*v)
	}
	return _u
}

// AddNextSeq adds value to the "next_seq" field.
func (_u *StreamUpdateOne) AddNextSeq(v int64) *StreamUpdateOne {
	_u.mutation.AddNextSeq(v)
	return _u
}

// SetCommittedSeq sets the "committed_seq" field.
func (_u *StreamUpdateOne) SetCommittedSeq(v int64) *StreamUpdateOne {
	_u.mutation.ResetCommittedSeq()
	_u.mutation.SetCommittedSeq(v)
	return _u
}

// SetNillableCommittedSeq sets the "committed_seq" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableCommittedSeq(v *int64) *StreamUpdateOne {
	if v != nil {
		_u.SetCommittedSeq(*v)
	}
	return _u
}

// AddCommittedSeq adds value to the "committed_seq" field.
func (_u *StreamUpdateOne) AddCommittedSeq(v int64) *StreamUpdateOne {
	_u.mutation.AddCommittedSeq(v)
	return _u
}

// SetPendingBytes sets the "pending_bytes" field.
func (_u *StreamUpdateOne) SetPendingBytes(v int64) *StreamUpdateOne {
	_u.mutation.ResetPendingBytes()
	_u.mutation.SetPendingBytes(v)
	return _u
}

// SetNillablePendingBytes sets the "pending_bytes" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillablePendingBytes(v *int64) *StreamUpdateOne {
	if v != nil {
		_u.SetPendingBytes(*v)
	}
	return _u
}

// AddPendingBytes adds value to the "pending_bytes" field.
func (_u *StreamUpdateOne) AddPendingBytes(v int64) *StreamUpdateOne {
	_u.mutation.AddPendingBytes(v)
	return _u
}

// SetRecoveryIssue sets the "recovery_issue" field.
func (_u *StreamUpdateOne) SetRecoveryIssue(v string) *StreamUpdateOne {
	_u.mutation.SetRecoveryIssue(v)
	return _u
}

// SetNillableRecoveryIssue sets the "recovery_issue" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableRecoveryIssue(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetRecoveryIssue(*v)
	}
	return _u
}

// Mutation returns the StreamMutation object of the builder.
func (_u *StreamUpdateOne) Mutation() *StreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the StreamUpdate builder.
func (_u *StreamUpdateOne) Where(ps ...predicate.Stream) *StreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StreamUpdateOne) Select(field string, fields ...string) *StreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Stream entity.
func (_u *StreamUpdateOne) Save(ctx context.Context) (*Stream, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StreamUpdateOne) SaveX(ctx context.Context) *Stream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StreamUpdateOne) check() error {
	if v, ok := _u.mutation.NextSeq(); ok {
		if err := stream.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.next_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommittedSeq(); ok {
		if err := stream.CommittedSeqValidator(v); err != nil {
			return &ValidationError{Name: "committed_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.committed_seq": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingBytes(); ok {
		if err := stream.PendingBytesValidator(v); err != nil {
			return &ValidationError{Name: "pending_bytes", err: fmt.Errorf(`ent: validator failed for field "Stream.pending_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *StreamUpdateOne) sqlSave(ctx context.Context) (_node *Stream, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stream.Table, stream.Columns, sqlgraph.NewFieldSpec(stream.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stream.FieldID)
		for _, f := range fields {
			if !stream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NextSeq(); ok {
		_spec.SetField(stream.FieldNextSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextSeq(); ok {
		_spec.AddField(stream.FieldNextSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommittedSeq(); ok {
		_spec.SetField(stream.FieldCommittedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommittedSeq(); ok {
		_spec.AddField(stream.FieldCommittedSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingBytes(); ok {
		_spec.SetField(stream.FieldPendingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingBytes(); ok {
		_spec.AddField(stream.FieldPendingBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveryIssue(); ok {
		_spec.SetField(stream.FieldRecoveryIssue, field.TypeString, value)
	}
	_node = &Stream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
