// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/stream"
)

// StreamCreate is the builder for creating a Stream entity.
type StreamCreate struct {
	config
	mutation *StreamMutation
	hooks    []Hook
}

// SetNextSeq sets the "next_seq" field.
func (_c *StreamCreate) SetNextSeq(v int64) *StreamCreate {
	_c.mutation.SetNextSeq(v)
	return _c
}

// SetNillableNextSeq sets the "next_seq" field if the given value is not nil.
func (_c *StreamCreate) SetNillableNextSeq(v *int64) *StreamCreate {
	if v != nil {
		_c.SetNextSeq(*v)
	}
	return _c
}

// SetCommittedSeq sets the "committed_seq" field.
func (_c *StreamCreate) SetCommittedSeq(v int64) *StreamCreate {
	_c.mutation.SetCommittedSeq(v)
	return _c
}

// SetNillableCommittedSeq sets the "committed_seq" field if the given value is not nil.
func (_c *StreamCreate) SetNillableCommittedSeq(v *int64) *StreamCreate {
	if v != nil {
		_c.SetCommittedSeq(*v)
	}
	return _c
}

// SetPendingBytes sets the "pending_bytes" field.
func (_c *StreamCreate) SetPendingBytes(v int64) *StreamCreate {
	_c.mutation.SetPendingBytes(v)
	return _c
}

// SetNillablePendingBytes sets the "pending_bytes" field if the given value is not nil.
func (_c *StreamCreate) SetNillablePendingBytes(v *int64) *StreamCreate {
	if v != nil {
		_c.SetPendingBytes(*v)
	}
	return _c
}

// SetRecoveryIssue sets the "recovery_issue" field.
func (_c *StreamCreate) SetRecoveryIssue(v string) *StreamCreate {
	_c.mutation.SetRecoveryIssue(v)
	return _c
}

// SetNillableRecoveryIssue sets the "recovery_issue" field if the given value is not nil.
func (_c *StreamCreate) SetNillableRecoveryIssue(v *string) *StreamCreate {
	if v != nil {
		_c.SetRecoveryIssue(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StreamCreate) SetID(v string) *StreamCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StreamMutation object of the builder.
func (_c *StreamCreate) Mutation() *StreamMutation {
	return _c.mutation
}

// Save creates the Stream in the database.
func (_c *StreamCreate) Save(ctx context.Context) (*Stream, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StreamCreate) SaveX(ctx context.Context) *Stream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StreamCreate) defaults() {
	if _, ok := _c.mutation.NextSeq(); !ok {
		v := stream.DefaultNextSeq
		_c.mutation.SetNextSeq(v)
	}
	if _, ok := _c.mutation.CommittedSeq(); !ok {
		v := stream.DefaultCommittedSeq
		_c.mutation.SetCommittedSeq(v)
	}
	if _, ok := _c.mutation.PendingBytes(); !ok {
		v := stream.DefaultPendingBytes
		_c.mutation.SetPendingBytes(v)
	}
	if _, ok := _c.mutation.RecoveryIssue(); !ok {
		v := stream.DefaultRecoveryIssue
		_c.mutation.SetRecoveryIssue(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StreamCreate) check() error {
	if _, ok := _c.mutation.NextSeq(); !ok {
		return &ValidationError{Name: "next_seq", err: errors.New(`ent: missing required field "Stream.next_seq"`)}
	}
	if v, ok := _c.mutation.NextSeq(); ok {
		if err := stream.NextSeqValidator(v); err != nil {
			return &ValidationError{Name: "next_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.next_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommittedSeq(); !ok {
		return &ValidationError{Name: "committed_seq", err: errors.New(`ent: missing required field "Stream.committed_seq"`)}
	}
	if v, ok := _c.mutation.CommittedSeq(); ok {
		if err := stream.CommittedSeqValidator(v); err != nil {
			return &ValidationError{Name: "committed_seq", err: fmt.Errorf(`ent: validator failed for field "Stream.committed_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PendingBytes(); !ok {
		return &ValidationError{Name: "pending_bytes", err: errors.New(`ent: missing required field "Stream.pending_bytes"`)}
	}
	if v, ok := _c.mutation.PendingBytes(); ok {
		if err := stream.PendingBytesValidator(v); err != nil {
			return &ValidationError{Name: "pending_bytes", err: fmt.Errorf(`ent: validator failed for field "Stream.pending_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecoveryIssue(); !ok {
		return &ValidationError{Name: "recovery_issue", err: errors.New(`ent: missing required field "Stream.recovery_issue"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := stream.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Stream.id": %w`, err)}
		}
	}
	return nil
}

func (_c *StreamCreate) sqlSave(ctx context.Context) (*Stream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Stream.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StreamCreate) createSpec() (*Stream, *sqlgraph.CreateSpec) {
	var (
		_node = &Stream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stream.Table, sqlgraph.NewFieldSpec(stream.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.NextSeq(); ok {
		_spec.SetField(stream.FieldNextSeq, field.TypeInt64, value)
		_node.NextSeq = value
	}
	if value, ok := _c.mutation.CommittedSeq(); ok {
		_spec.SetField(stream.FieldCommittedSeq, field.TypeInt64, value)
		_node.CommittedSeq = value
	}
	if value, ok := _c.mutation.PendingBytes(); ok {
		_spec.SetField(stream.FieldPendingBytes, field.TypeInt64, value)
		_node.PendingBytes = value
	}
	if value, ok := _c.mutation.RecoveryIssue(); ok {
		_spec.SetField(stream.FieldRecoveryIssue, field.TypeString, value)
		_node.RecoveryIssue = value
	}
	return _node, _spec
}

// StreamCreateBulk is the builder for creating many Stream entities in bulk.
type StreamCreateBulk struct {
	config
	err      error
	builders []*StreamCreate
}

// Save creates the Stream entities in the database.
func (_c *StreamCreateBulk) Save(ctx context.Context) ([]*Stream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Stream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StreamCreateBulk) SaveX(ctx context.Context) []*Stream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
