// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/stream"
)

// Stream is the model entity for the Stream schema.
type Stream struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// NextSeq holds the value of the "next_seq" field.
	NextSeq int64 `json:"next_seq,omitempty"`
	// CommittedSeq holds the value of the "committed_seq" field.
	CommittedSeq int64 `json:"committed_seq,omitempty"`
	// PendingBytes holds the value of the "pending_bytes" field.
	PendingBytes int64 `json:"pending_bytes,omitempty"`
	// RecoveryIssue holds the value of the "recovery_issue" field.
	RecoveryIssue string `json:"recovery_issue,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stream.FieldNextSeq, stream.FieldCommittedSeq, stream.FieldPendingBytes:
			values[i] = new(sql.NullInt64)
		case stream.FieldID, stream.FieldRecoveryIssue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stream fields.
func (_m *Stream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stream.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case stream.FieldNextSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_seq", values[i])
			} else if value.Valid {
				_m.NextSeq = value.Int64
			}
		case stream.FieldCommittedSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field committed_seq", values[i])
			} else if value.Valid {
				_m.CommittedSeq = value.Int64
			}
		case stream.FieldPendingBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_bytes", values[i])
			} else if value.Valid {
				_m.PendingBytes = value.Int64
			}
		case stream.FieldRecoveryIssue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_issue", values[i])
			} else if value.Valid {
				_m.RecoveryIssue = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Stream.
// This includes values selected through modifiers, order, etc.
func (_m *Stream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Stream.
// Note that you need to call Stream.Unwrap() before calling this method if this Stream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Stream) Update() *StreamUpdateOne {
	return NewStreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Stream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Stream) Unwrap() *Stream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Stream) String() string {
	var builder strings.Builder
	builder.WriteString("Stream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("next_seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextSeq))
	builder.WriteString(", ")
	builder.WriteString("committed_seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommittedSeq))
	builder.WriteString(", ")
	builder.WriteString("pending_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingBytes))
	builder.WriteString(", ")
	builder.WriteString("recovery_issue=")
	builder.WriteString(_m.RecoveryIssue)
	builder.WriteByte(')')
	return builder.String()
}

// Streams is a parsable slice of Stream.
type Streams []*Stream
