// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/predicate"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/task"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressSeq sets the "progress_seq" field.
func (_u *TaskUpdate) SetProgressSeq(v int64) *TaskUpdate {
	_u.mutation.ResetProgressSeq()
	_u.mutation.SetProgressSeq(v)
	return _u
}

// SetNillableProgressSeq sets the "progress_seq" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableProgressSeq(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetProgressSeq(*v)
	}
	return _u
}

// AddProgressSeq adds value to the "progress_seq" field.
func (_u *TaskUpdate) AddProgressSeq(v int64) *TaskUpdate {
	_u.mutation.AddProgressSeq(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *TaskUpdate) SetResult(v []byte) *TaskUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *TaskUpdate) ClearResult() *TaskUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetAcknowledged sets the "acknowledged" field.
func (_u *TaskUpdate) SetAcknowledged(v bool) *TaskUpdate {
	_u.mutation.SetAcknowledged(v)
	return _u
}

// SetNillableAcknowledged sets the "acknowledged" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAcknowledged(v *bool) *TaskUpdate {
	if v != nil {
		_u.SetAcknowledged(*v)
	}
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressSeq(); ok {
		if err := task.ProgressSeqValidator(v); err != nil {
			return &ValidationError{Name: "progress_seq", err: fmt.Errorf(`ent: validator failed for field "Task.progress_seq": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressSeq(); ok {
		_spec.SetField(task.FieldProgressSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProgressSeq(); ok {
		_spec.AddField(task.FieldProgressSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(task.FieldResult, field.TypeBytes, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(task.FieldResult, field.TypeBytes)
	}
	if value, ok := _u.mutation.Acknowledged(); ok {
		_spec.SetField(task.FieldAcknowledged, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressSeq sets the "progress_seq" field.
func (_u *TaskUpdateOne) SetProgressSeq(v int64) *TaskUpdateOne {
	_u.mutation.ResetProgressSeq()
	_u.mutation.SetProgressSeq(v)
	return _u
}

// SetNillableProgressSeq sets the "progress_seq" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableProgressSeq(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetProgressSeq(*v)
	}
	return _u
}

// AddProgressSeq adds value to the "progress_seq" field.
func (_u *TaskUpdateOne) AddProgressSeq(v int64) *TaskUpdateOne {
	_u.mutation.AddProgressSeq(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *TaskUpdateOne) SetResult(v []byte) *TaskUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *TaskUpdateOne) ClearResult() *TaskUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetAcknowledged sets the "acknowledged" field.
func (_u *TaskUpdateOne) SetAcknowledged(v bool) *TaskUpdateOne {
	_u.mutation.SetAcknowledged(v)
	return _u
}

// SetNillableAcknowledged sets the "acknowledged" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAcknowledged(v *bool) *TaskUpdateOne {
	if v != nil {
		_u.SetAcknowledged(*v)
	}
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressSeq(); ok {
		if err := task.ProgressSeqValidator(v); err != nil {
			return &ValidationError{Name: "progress_seq", err: fmt.Errorf(`ent: validator failed for field "Task.progress_seq": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressSeq(); ok {
		_spec.SetField(task.FieldProgressSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProgressSeq(); ok {
		_spec.AddField(task.FieldProgressSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(task.FieldResult, field.TypeBytes, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(task.FieldResult, field.TypeBytes)
	}
	if value, ok := _u.mutation.Acknowledged(); ok {
		_spec.SetField(task.FieldAcknowledged, field.TypeBool, value)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
