// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Zxilly/bifurcation/services/daemon/internal/state/ent/task"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetPayloadHash sets the "payload_hash" field.
func (_c *TaskCreate) SetPayloadHash(v string) *TaskCreate {
	_c.mutation.SetPayloadHash(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TaskCreate) SetKind(v string) *TaskCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *TaskCreate) SetPayload(v []byte) *TaskCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetBindingEpoch sets the "binding_epoch" field.
func (_c *TaskCreate) SetBindingEpoch(v int64) *TaskCreate {
	_c.mutation.SetBindingEpoch(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskCreate) SetStatus(v task.Status) *TaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TaskCreate) SetNillableStatus(v *task.Status) *TaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgressSeq sets the "progress_seq" field.
func (_c *TaskCreate) SetProgressSeq(v int64) *TaskCreate {
	_c.mutation.SetProgressSeq(v)
	return _c
}

// SetNillableProgressSeq sets the "progress_seq" field if the given value is not nil.
func (_c *TaskCreate) SetNillableProgressSeq(v *int64) *TaskCreate {
	if v != nil {
		_c.SetProgressSeq(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *TaskCreate) SetResult(v []byte) *TaskCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetAcknowledged sets the "acknowledged" field.
func (_c *TaskCreate) SetAcknowledged(v bool) *TaskCreate {
	_c.mutation.SetAcknowledged(v)
	return _c
}

// SetNillableAcknowledged sets the "acknowledged" field if the given value is not nil.
func (_c *TaskCreate) SetNillableAcknowledged(v *bool) *TaskCreate {
	if v != nil {
		_c.SetAcknowledged(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v string) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := task.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProgressSeq(); !ok {
		v := task.DefaultProgressSeq
		_c.mutation.SetProgressSeq(v)
	}
	if _, ok := _c.mutation.Acknowledged(); !ok {
		v := task.DefaultAcknowledged
		_c.mutation.SetAcknowledged(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.PayloadHash(); !ok {
		return &ValidationError{Name: "payload_hash", err: errors.New(`ent: missing required field "Task.payload_hash"`)}
	}
	if v, ok := _c.mutation.PayloadHash(); ok {
		if err := task.PayloadHashValidator(v); err != nil {
			return &ValidationError{Name: "payload_hash", err: fmt.Errorf(`ent: validator failed for field "Task.payload_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Task.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := task.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Task.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Task.payload"`)}
	}
	if _, ok := _c.mutation.BindingEpoch(); !ok {
		return &ValidationError{Name: "binding_epoch", err: errors.New(`ent: missing required field "Task.binding_epoch"`)}
	}
	if v, ok := _c.mutation.BindingEpoch(); ok {
		if err := task.BindingEpochValidator(v); err != nil {
			return &ValidationError{Name: "binding_epoch", err: fmt.Errorf(`ent: validator failed for field "Task.binding_epoch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProgressSeq(); !ok {
		return &ValidationError{Name: "progress_seq", err: errors.New(`ent: missing required field "Task.progress_seq"`)}
	}
	if v, ok := _c.mutation.ProgressSeq(); ok {
		if err := task.ProgressSeqValidator(v); err != nil {
			return &ValidationError{Name: "progress_seq", err: fmt.Errorf(`ent: validator failed for field "Task.progress_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Acknowledged(); !ok {
		return &ValidationError{Name: "acknowledged", err: errors.New(`ent: missing required field "Task.acknowledged"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := task.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Task.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Task.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PayloadHash(); ok {
		_spec.SetField(task.FieldPayloadHash, field.TypeString, value)
		_node.PayloadHash = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(task.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(task.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.BindingEpoch(); ok {
		_spec.SetField(task.FieldBindingEpoch, field.TypeInt64, value)
		_node.BindingEpoch = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProgressSeq(); ok {
		_spec.SetField(task.FieldProgressSeq, field.TypeInt64, value)
		_node.ProgressSeq = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(task.FieldResult, field.TypeBytes, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Acknowledged(); ok {
		_spec.SetField(task.FieldAcknowledged, field.TypeBool, value)
		_node.Acknowledged = value
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
